Repository openshift/api, pull requests merged in 2018-11, with the labels that each got.

#121 fix object meta field in BuildList
  config/v1/types.go
  config/v1/types_swagger_doc_generated.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#119 add internal registry hostname to serviceaccount controller config
  openshiftcontrolplane/v1/types.go
  openshiftcontrolplane/v1/types_swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#122 switch build config format back to old style selector
  openshiftcontrolplane/v1/types.go
  openshiftcontrolplane/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#123 add metav1 to config to allow working client
  config/v1/register.go
Labels: approved, lgtm, size/XS

#127 api: Move ClusterVersion/ClusterOperator into config.openshift.io
  config/v1/register.go
  config/v1/types_cluster_operator.go
  config/v1/types_cluster_version.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#133 Fix openapi for cluster operator
  config/v1/types_cluster_operator.go
Labels: approved, size/XS

#134 align godoc and field
  config/v1/types_cluster_operator.go
Labels: approved, lgtm, size/XS

#132 add externalregistryhost slice to cluster config
  config/v1/types_image.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#135 rename static pod deployment to revision for clarity
  operator/v1/types.go
  operator/v1/types_swagger_doc_generated.go
  operator/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#137 add observed generation to operator v1
  operator/v1/types.go
  operator/v1/types_swagger_doc_generated.go
Labels: approved, lgtm, size/S

#139 Add ingress domain
  config/v1/types_ingress.go
Labels: approved, lgtm, size/XS

#140 Move service cert signer to operator v1 spec and status
  servicecertsigner/v1alpha1/types.go
  servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  servicecertsigner/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L
