Repository openshift/api, pull requests merged in 2018-12, with the labels that each got.

#142 config: Remove Namespace for Config References
  config/v1/types.go
  config/v1/types_swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#146 Add base domain to DNS config
  config/v1/types_dns.go
Labels: approved, lgtm, size/XS

#129 feat(config/types_oauth.go): add oauth server config types
  config/v1/types.go
  config/v1/types_oauth.go
  config/v1/types_swagger_doc_generated.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#145 Add cloud provider name to infra config
  config/v1/types_infrastructure.go
Labels: approved, lgtm, size/XS

#141 config: add Network type
  config/v1/types_network.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#147 Add oauthMetadata and webhookTokenAuthenticators to auth config
  config/v1/types_authentication.go
  config/v1/types_oauth.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M
