Repository openshift/api, pull requests merged in 2018-08, with the labels that each got.

#76 Add AdminConsolePublicURL to webconsole config
  webconsole/v1/generated.pb.go
  webconsole/v1/generated.proto
  webconsole/v1/types.go
  webconsole/v1/types_swagger_doc_generated.go
Labels: lgtm, size/L

#82 [release-3.9] Add admin console URL to web console config
  webconsole/v1/generated.pb.go
  webconsole/v1/generated.proto
  webconsole/v1/types.go
  webconsole/v1/types_swagger_doc_generated.go
Labels: lgtm, size/L

#83 [release-3.10] Add admin console URL to web console config
  webconsole/v1/generated.pb.go
  webconsole/v1/generated.proto
  webconsole/v1/types.go
  webconsole/v1/types_swagger_doc_generated.go
Labels: lgtm, size/L

#84 add network annotation constants
  network/v1/constants.go
Labels: lgtm, size/S

#79 Images are themselves manifests, and reference a config blob
  image/v1/generated.pb.go
  image/v1/generated.proto
  image/v1/types.go
  image/v1/types_swagger_doc_generated.go
  image/v1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#85 make external gitinfo match internal
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/types_swagger_doc_generated.go
  build/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#87 add missing template annotation consts
  template/v1/consts.go
Labels: approved, lgtm, size/S

#77 pick up missing groups to install found when using in oc
  install.go
Labels: approved, lgtm, size/XS

#89 apps: add missing consts and vars
  apps/v1/consts.go
  apps/v1/deprecated_consts.go
Labels: approved, lgtm, size/L

#91 clean up owners
  OWNERS
Labels: approved, lgtm, size/XS
