Repository openshift/api, pull requests merged in 2018-10, with the labels that each got.

#103 Rename VersionAvailablity to VersionAvailability
  operator/v1alpha1/types.go
  operator/v1alpha1/types_swagger_doc_generated.go
  operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#106 remove config proto tags
  openshiftcontrolplane/v1/types.go
Labels: approved, lgtm, size/M

#109 operator: add imagePullPolicy to allow override the operator image pull policy
  operator/v1alpha1/types.go
  operator/v1alpha1/types_swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#110 add status conditions to match CVO ClusterOperator
  operator/v1alpha1/types.go
Labels: approved, lgtm, size/XS

#111 add imageconfig
  config/v1/register.go
  config/v1/types.go
  config/v1/types_swagger_doc_generated.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#112 Fix capitalization of vxlanPort
  openshiftcontrolplane/v1/types.go
Labels: approved, lgtm

#116 add static pod operator status
  operator/v1alpha1/types.go
  operator/v1alpha1/types_swagger_doc_generated.go
  operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#113 Build Controller CA Bundles
  config/v1/register.go
  config/v1/types.go
  config/v1/types_swagger_doc_generated.go
  config/v1/zz_generated.deepcopy.go
  openshiftcontrolplane/v1/types.go
  openshiftcontrolplane/v1/types_swagger_doc_generated.go
  openshiftcontrolplane/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L
