Repository openshift/api, pull requests merged in 2018-05, with the labels that each got.

#47 bump to 1.10.2
  glide.lock
  glide.yaml
  vendor/k8s.io/code-generator/Godeps/Godeps.json
Labels: size/XL

#45 add config API group for common config
  Makefile
  config/v1/doc.go
  config/v1/generated.pb.go
  config/v1/generated.proto
  config/v1/register.go
  config/v1/types.go
  config/v1/types_swagger_doc_generated.go
  config/v1/zz_generated.deepcopy.go
  hack/lib/init.sh
  hack/update-deepcopy.sh
  webconsole/v1/generated.pb.go
  webconsole/v1/generated.proto
  webconsole/v1/types.go
  webconsole/v1/types_swagger_doc_generated.go
  webconsole/v1/zz_generated.deepcopy.go
Labels: lgtm, size/XXL

#46 R.I.P. Policy Objects
  authorization/v1/codec.go
  authorization/v1/generated.pb.go
  authorization/v1/generated.proto
  authorization/v1/register.go
  authorization/v1/types.go
  authorization/v1/types_swagger_doc_generated.go
  authorization/v1/zz_generated.deepcopy.go
Labels: lgtm, size/XXL

#48 add alpha common operator types
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  operator/v1alpha1/doc.go
  operator/v1alpha1/generated.pb.go
  operator/v1alpha1/generated.proto
  operator/v1alpha1/register.go
  operator/v1alpha1/types.go
  operator/v1alpha1/types_swagger_doc_generated.go
  operator/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/XXL

#49 add types for service serving cert signer controller
  Makefile
  config/v1/generated.pb.go
  config/v1/generated.proto
  config/v1/types.go
  config/v1/types_swagger_doc_generated.go
  config/v1/zz_generated.deepcopy.go
  hack/lib/init.sh
  hack/update-deepcopy.sh
  servicecertsigner/v1alpha1/doc.go
  servicecertsigner/v1alpha1/generated.pb.go
  servicecertsigner/v1alpha1/generated.proto
  servicecertsigner/v1alpha1/register.go
  servicecertsigner/v1alpha1/types.go
  servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  servicecertsigner/v1alpha1/zz_generated.deepcopy.go
Labels: size/XXL

#52 SCC: mark AllowFlexVolumes as optional field
  security/v1/generated.proto
  security/v1/types.go
Labels: lgtm, size/XS

#53 fix up operator types for clarity
  operator/v1alpha1/generated.pb.go
  operator/v1alpha1/generated.proto
  operator/v1alpha1/register.go
  operator/v1alpha1/types.go
  operator/v1alpha1/types_swagger_doc_generated.go
  operator/v1alpha1/zz_generated.deepcopy.go
  servicecertsigner/v1alpha1/generated.pb.go
  servicecertsigner/v1alpha1/generated.proto
  servicecertsigner/v1alpha1/types.go
  servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  servicecertsigner/v1alpha1/zz_generated.deepcopy.go
Labels: size/XXL

#55 fix registration for served API
  servicecertsigner/v1alpha1/register.go
Labels: lgtm, size/XS
