Repository openshift/api, pull requests merged in 2018-06, with the labels that each got.

#51 Make github hide generated files in diffs
  .gitattributes
Labels: size/XS

#59 list doesn't make sense for subresources
  image/v1/types.go
Labels: lgtm, size/XS

#43 Adding ConfigMap build sources to api
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/types_swagger_doc_generated.go
  build/v1/zz_generated.deepcopy.go
Labels: lgtm, size/XL

#44 Add 'Paused' to ImageChangeTrigger for BuildConfig
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/types_swagger_doc_generated.go
Labels: size/XL

#38 SCC: add {Default,}AllowPrivilegeEscalation options
  security/v1/generated.pb.go
  security/v1/generated.proto
  security/v1/types.go
  security/v1/types_swagger_doc_generated.go
  security/v1/zz_generated.deepcopy.go
Labels: size/L

#62 SCC: add {Default,}AllowPrivilegeEscalation options to pre-3.11 branch
  security/v1/generated.pb.go
  security/v1/generated.proto
  security/v1/types.go
  security/v1/types_swagger_doc_generated.go
  security/v1/zz_generated.deepcopy.go
Labels: size/L

#63 fix type registration for templates
  template/v1/register.go
Labels: lgtm, size/XS

#65 Rebase to 11 ga
  glide.lock
  glide.yaml
  vendor/github.com/json-iterator/go/Gopkg.lock
  vendor/github.com/json-iterator/go/api_tests/config_test.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_native.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/value_tests/slice_test.go
  vendor/k8s.io/api/Godeps/Godeps.json
  vendor/k8s.io/apimachinery/Godeps/Godeps.json
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/group_version_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types_test.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json_test.go
  vendor/k8s.io/code-generator/Godeps/Godeps.json
  vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/packages.go
  vendor/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
Labels: size/L
