Repository openshift/api, pull requests merged in 2018-07, with the labels that each got.

#66 add config types for other SCS controllers
  servicecertsigner/v1alpha1/generated.pb.go
  servicecertsigner/v1alpha1/generated.proto
  servicecertsigner/v1alpha1/register.go
  servicecertsigner/v1alpha1/types.go
  servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  servicecertsigner/v1alpha1/zz_generated.deepcopy.go
Labels: size/XXL

#67 create install functions based on new runtime.Scheme
  .travis.yml
  Makefile
  apps/install.go
  apps/v1/legacy.go
  apps/v1/register.go
  authorization/install.go
  authorization/v1/legacy.go
  authorization/v1/register.go
  build/install.go
  build/v1/legacy.go
  build/v1/register.go
  config/install.go
  config/v1/register.go
  image/install.go
  image/v1/legacy.go
  image/v1/register.go
  install.go
  network/install.go
  network/v1/generated.pb.go
  network/v1/generated.proto
  network/v1/legacy.go
  network/v1/register.go
  oauth/install.go
  oauth/v1/legacy.go
  oauth/v1/register.go
  operator/install.go
  operator/v1alpha1/register.go
  pkg/testing/deepcopy_test.go
  pkg/testing/doc.go
  project/install.go
  project/v1/generated.pb.go
  project/v1/generated.proto
  project/v1/legacy.go
  project/v1/register.go
  quota/install.go
  quota/v1/generated.pb.go
  quota/v1/generated.proto
  quota/v1/legacy.go
  quota/v1/register.go
  route/install.go
  route/v1/generated.pb.go
  route/v1/generated.proto
  route/v1/legacy.go
  route/v1/register.go
  security/install.go
  security/v1/legacy.go
  security/v1/register.go
  servicecertsigner/install.go
  servicecertsigner/v1alpha1/register.go
  template/install.go
  template/v1/legacy.go
  template/v1/register.go
  user/install.go
  user/v1/generated.pb.go
  user/v1/generated.proto
  user/v1/legacy.go
  user/v1/register.go
  webconsole/install.go
  webconsole/v1/register.go
Labels: do-not-merge/hold, size/XXL

#56 Add an ImageStreamLayers object for returning layers of a stream
  image/v1/generated.pb.go
  image/v1/generated.proto
  image/v1/register.go
  image/v1/types.go
  image/v1/types_swagger_doc_generated.go
  image/v1/zz_generated.deepcopy.go
Labels: lgtm, size/XXL

#69 minor fixes for generator and package name
  authorization/install.go
  image/v1/types.go
Labels: size/XS

#71 add OOMKilled failure reason to build
  build/v1/consts.go
Labels: lgtm, size/XS

#72 describe PR process for coordinating API changes
  README.md
Labels: size/S

#73 change operator alpha types based on SSCS experience
  operator/v1alpha1/generated.pb.go
  operator/v1alpha1/generated.proto
  operator/v1alpha1/types.go
  operator/v1alpha1/types_swagger_doc_generated.go
  operator/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#74 Revert " change operator alpha types based on SSCS experience"
  operator/v1alpha1/generated.pb.go
  operator/v1alpha1/generated.proto
  operator/v1alpha1/types.go
  operator/v1alpha1/types_swagger_doc_generated.go
  operator/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#64 add HostSubnet.EgressCIDRs
  network/v1/generated.pb.go
  network/v1/generated.proto
  network/v1/types.go
  network/v1/types_swagger_doc_generated.go
  network/v1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#60 SCC: add {AllowedUnsafe,Forbidden}Sysctls
  security/v1/generated.pb.go
  security/v1/generated.proto
  security/v1/types.go
  security/v1/types_swagger_doc_generated.go
  security/v1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#75 v1.11.1
  glide.lock
  glide.yaml
  vendor/k8s.io/api/Godeps/Godeps.json
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.proto
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
Labels: size/XXL

#57 adding vxlanPort the the ClusterNetwork Object
  network/v1/generated.pb.go
  network/v1/generated.proto
  network/v1/types.go
  network/v1/types_swagger_doc_generated.go
  network/v1/zz_generated.deepcopy.go
Labels: lgtm, size/L
