Repository openshift/api, pull requests merged in 2019-02, with the labels that each got.

#193 migrate authentication operator config
  operator/v1/register.go
  operator/v1/types_authentication.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#194 fixup kubeapiserver swagger
  operator/v1/types_kubeapiserver.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#188 add features api for feature gates
  config/v1/register.go
  config/v1/type_features.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#195 remove option for enabling oapi
  openshiftcontrolplane/v1/types.go
  openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#196 Scheduler types
  operator/v1/register.go
  operator/v1/types_scheduler.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#201 Add OsinServerConfig
  osin/v1/register.go
  osin/v1/types.go
  osin/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#203 Add service-ca operator config
  operator/v1/register.go
  operator/v1/types_serviceca.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#205 add explicit option for enabling admission plugins
  config/v1/types.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#204 Add API changes for Registries CRD
  config/v1/register.go
  config/v1/types_registries.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#192 Remove Search Registries for Builds
  config/v1/types_build.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#202 config/v1: add public and private zones to DNSSpec
  config/v1/types_dns.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#207 move container runtime registries config under the image api
  config/v1/register.go
  config/v1/types_image.go
  config/v1/types_registries.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#209 Add Service Catalog operator types
  operator/v1/register.go
  operator/v1/types_servicecatalogapiserver.go
  operator/v1/types_servicecatalogcontrollermanager.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#210 update the scheduler API for static pods
  operator/v1/types_scheduler.go
  operator/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#206 add clusteroperator Upgradeable conditions
  config/v1/types_cluster_operator.go
Labels: approved, lgtm, size/S

#211 update features API to reduce changes
  config/v1/type_features.go
  config/v1/types_features.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#213 config/v1: fix typo in DefaultDisabledKubeFeatures comment
  config/v1/types_features.go
Labels: approved, lgtm, size/XS

#208 Remove RegistriesConfig from builds
  config/v1/types_build.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#212 Change Console Status PublicHostname to ConsoleURL
  config/v1/types_console.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#220 Modify operator fields to be optional
  operator/v1/types.go
Labels: approved, lgtm, size/XS

#224 create a map of FeatureSets
  config/v1/types_features.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M
