Repository openshift/api, pull requests merged in 2019-05, with the labels that each got.

#303 add more nullable tags for SCCs take 3
  security/v1/generated.proto
  security/v1/types.go
Labels: approved, lgtm, size/XS

#306 Add nullable tags to RBR
  authorization/v1/generated.proto
  authorization/v1/types.go
Labels: approved, lgtm, size/XS

#308 config/v1/types_infrastructure: Split apiServerURL intro external/internal
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#300 config/v1/types_infrastructure: Add AWS Region
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#307 make bparees an api approver
  OWNERS
Labels: approved, lgtm, size/XS

#309 Update Dockerfile.build to fedora:29 base
  Dockerfile.build
  hack/update-protobuf.sh
Labels: approved, lgtm, size/XS

#302 Add missing kubebuilder tag for SecurityContextConstraint
  security/v1/generated.proto
  security/v1/types.go
Labels: approved, lgtm, size/XS

#271 Bug 1693685: Fixing build retention API doc
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#310 update weight default in route to service
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, ok-to-test, size/XS

#311 operator/ingress: Default Azure to LoadBalancer
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#315 operator/v1: add latestAvailableRevisionReason
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#304 Add Custom product name and logo to api
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#323 config: Fix Image InsecureRegistries Doc
  config/v1/types_image.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#284 Add Kuryr-Kubernetes options and network type
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#327 add session secrets used by oauthserver
  osin/v1/register.go
  osin/v1/types.go
  osin/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#320 Update console api with statuspage.io ID option
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#328 operator/ingress: add kubebuilder markers
  operator/v1/types_ingress.go
Labels: approved, lgtm, size/XS

#329 operator: fix kubebuilder validation marker location
  operator/v1/types.go
Labels: approved, lgtm, size/XS
