Repository openshift/api, pull requests merged in 2019-06, with the labels that each got.

#316 operator/ingress: Default GCP to LoadBalancer
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#333 add annotations uses by oas and ocm to communicate about scc
  security/v1/consts.go
Labels: approved, lgtm, size/S

#332 add unidling APIs
  unidiling/v1alpha1/types.go
Labels: approved, lgtm, size/M

#334 typo fix
  unidling/v1alpha1/types.go
Labels: approved, lgtm, size/XS

#337 add constants for image annotations
  image/v1/consts.go
  image/v1/types.go
Labels: approved, lgtm, size/M

#339 Add project annotation used by scheduler, apiserver and oc
  project/v1/types.go
Labels: approved, lgtm, size/XS

#340 Add build annotations used by controller and oc
  build/v1/consts.go
Labels: approved, lgtm, size/S

#343 add more build constants that are API
  build/v1/consts.go
Labels: approved, lgtm, size/M

#335 Add ProxyStatus to config/v1/types_proxy
  config/v1/types_proxy.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#336 operator/dns: add kubebuilder tags
  operator/v1/types_dns.go
Labels: approved, lgtm, size/XS

#342 Add MTU to network.ClusterNetwork
  network/v1/generated.pb.go
  network/v1/generated.proto
  network/v1/types.go
  network/v1/zz_generated.deepcopy.go
  network/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#318 Add api types for console extension resources and console server config
  console/OWNERS
  console/install.go
  console/v1/doc.go
  console/v1/register.go
  console/v1/types.go
  console/v1/types_console_cli_download.go
  console/v1/types_console_link.go
  console/v1/types_console_notification.go
  console/v1/zz_generated.deepcopy.go
  console/v1/zz_generated.swagger_doc_generated.go
  hack/lib/init.sh
  hack/update-deepcopy.sh
Labels: approved, lgtm, size/L

#344 add more of the build API surface area
  build/v1/consts.go
Labels: approved, lgtm, size/M

#345 add image signature constant
  image/v1/consts.go
Labels: approved, lgtm, size/XS

#322 operator/ingress: Add SecuritySpec API
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#349 Reverts PR #322: Adds SecuritySpec API
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#351 auth: add UserKind and GroupKind consts
  authorization/v1/types.go
Labels: approved, lgtm, size/XS

#352 auth: add scopes key
  authorization/v1/types.go
Labels: approved, lgtm, size/XS

#312 operator/ingress: Add load balancer type
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#346 Remove wildcard comments from proxy.
  config/v1/types_proxy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#341 Update comments/docs on console resources
  config/v1/types_console.go
  config/v1/zz_generated.swagger_doc_generated.go
  operator/v1/types_console.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#347 config/network: add ExternalIPs field
  config/v1/types_network.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#354 Add ImageContentSourcePolicy to operator/v1alpha1
  operator/v1alpha1/types_image_content_source_policy.go
  operator/v1alpha1/zz_generated.deepcopy.go
  operator/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#356 Add ImageContentSourcePolicy to register.go
  operator/v1alpha1/register.go
Labels: approved, lgtm, size/XS
