Repository openshift/api, pull requests merged in 2019-11, with the labels that each got.

#482 Add IntermediateCertFile to ServiceServingCertSignerConfig
  servicecertsigner/v1alpha1/types.go
  servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#507 Bug 1767926: Fix targetResource in ConsoleYAMLSample CRD
  console/v1/0000_10_consoleyamlsample.crd.yaml
  console/v1/types_console_yaml_sample.go
  console/v1/zz_generated.swagger_doc_generated.go
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#494 Bug 1755306 - Revert the unintended vxlan api backport
  .travis.yml
  network/v1/generated.pb.go
  network/v1/generated.proto
  network/v1/types.go
  network/v1/types_swagger_doc_generated.go
  network/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#509 Bug 1768542: Add `snippet` flag to ConsoleYAMLSample CRD
  console/v1/0000_10_consoleyamlsample.crd.yaml
  console/v1/types_console_yaml_sample.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#508 apiserver: make note of the supported tls profiles
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/types_apiserver.go
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.swagger_doc_generated.go
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
Labels: approved, lgtm, size/M

#441 Adds Server type to dnses.operator.openshift.io API
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#500 config/v1/types_cluster_operator: "the kube ecosystem" -> "the Kubernetes ecosystem"
  config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/v1/types_cluster_operator.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#501 config/v1/types_cluster_operator: ClusterOperatorStatus doc wordsmithing
  config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_operator.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#512 Bug 1767954: Add CRDs to update and verify targets
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#515 Remove ExperimentalCriticalPodAnnotation from featureflags
  config/v1/types_feature.go
Labels: approved, lgtm, size/M

#516 Removes TLSSecurityProfile from feature gate
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#513 move samples CRD to openshift api
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  install.go
  samples/install.go
  samples/v1/0000_10_samplesconfig.crd.yaml
  samples/v1/doc.go
  samples/v1/generated.pb.go
  samples/v1/generated.proto
  samples/v1/register.go
  samples/v1/types_config.go
  samples/v1/zz_generated.deepcopy.go
  samples/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#504 Enable SCTP feature gate
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#518 operator: fix description for openshift apiserver spec and status
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/types_openshiftapiserver.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#517 add status subresource to samples config crd
  samples/v1/0000_10_samplesconfig.crd.yaml
Labels: approved, lgtm, size/XS

#520 samples: add pathMergeKey and pathStrategy tags
  samples/v1/generated.proto
  samples/v1/types_config.go
Labels: approved, lgtm, size/S

#519 Bug 1769008: Migrating imageregistry api definitions.
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  imageregistry/install.go
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/doc.go
  imageregistry/v1/register.go
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
  install.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#510 config/v1/types_cluster_operator: Fix "Degraded indicated" -> "Degraded indicates"
  config/v1/types_cluster_operator.go
Labels: approved, lgtm, size/XS

#499 config/v1/types_cluster_operator: Fix "spec hold the" typo
  config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/v1/types_cluster_operator.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#529 Add description to spec and status fields for kube operators
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/types_kubeapiserver.go
  operator/v1/types_kubecontrollermanager.go
  operator/v1/types_scheduler.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S
