Repository openshift/api, pull requests merged in 2019-03, with the labels that each got.

#226 operator/v1: add omitempty where applicable
  config/v1/types.go
  config/v1/types_apiserver.go
  config/v1/types_authentication.go
  config/v1/types_build.go
  config/v1/types_console.go
  config/v1/types_dns.go
  config/v1/types_features.go
  config/v1/types_image.go
  config/v1/types_infrastructure.go
  config/v1/types_ingress.go
  config/v1/types_network.go
  config/v1/types_oauth.go
  config/v1/types_project.go
  config/v1/types_proxy.go
  config/v1/types_scheduling.go
  operator/v1/types.go
  operator/v1/types_authentication.go
  operator/v1/types_console.go
  operator/v1/types_etcd.go
  operator/v1/types_kubeapiserver.go
  operator/v1/types_kubecontrollermanager.go
  operator/v1/types_openshiftapiserver.go
  operator/v1/types_openshiftcontrollermanager.go
  operator/v1/types_scheduler.go
  operator/v1/types_serviceca.go
  operator/v1/types_servicecatalogapiserver.go
  operator/v1/types_servicecatalogcontrollermanager.go
Labels: approved, lgtm, size/L

#230 rename Scheduling type to Scheduler
  config/v1/register.go
  config/v1/types_scheduling.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#227 config/operator: fix omitempty, +optional, +nullable without behaviour change
  config/v1/types.go
  config/v1/types_apiserver.go
  config/v1/types_authentication.go
  config/v1/types_build.go
  config/v1/types_cluster_operator.go
  config/v1/types_cluster_version.go
  config/v1/types_console.go
  config/v1/types_dns.go
  config/v1/types_features.go
  config/v1/types_image.go
  config/v1/types_infrastructure.go
  config/v1/types_ingress.go
  config/v1/types_network.go
  config/v1/types_oauth.go
  config/v1/types_project.go
  config/v1/types_proxy.go
  config/v1/types_scheduling.go
  operator/v1/types.go
  operator/v1/types_authentication.go
  operator/v1/types_console.go
  operator/v1/types_etcd.go
  operator/v1/types_kubeapiserver.go
  operator/v1/types_kubecontrollermanager.go
  operator/v1/types_openshiftapiserver.go
  operator/v1/types_openshiftcontrollermanager.go
  operator/v1/types_scheduler.go
  operator/v1/types_serviceca.go
  operator/v1/types_servicecatalogapiserver.go
  operator/v1/types_servicecatalogcontrollermanager.go
Labels: approved, lgtm, size/L

#228 config/v1: avoid null values for pointers and slices
  config/v1/types_cluster_version.go
  operator/v1/types_servicecatalogcontrollermanager.go
Labels: approved, lgtm, size/S

#233 Add pattern validation to operatorspec managementstate
  operator/v1/types.go
Labels: approved, lgtm, size/XS

#219 operator/v1: add ingresscontroller
  operator/v1/register.go
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#232 operator/v1: remove optional from managementState
  operator/v1/types.go
Labels: approved, lgtm, size/XS

#237 config: add nullable to NetworkStatus
  config/v1/types_network.go
Labels: approved, lgtm, size/XS

#239 Make config.NetworkStatus fields omitempty
  config/v1/types_network.go
Labels: approved, lgtm, size/S

#238 operator/ingress: fix endpoint publishing strategy optionality
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#244 update feature gates to match desired values
  config/v1/types_features.go
Labels: approved, lgtm, size/S

#241 operator/ingress: add condition types
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#215 Operator: add Network type
  operator/v1/register.go
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#222 Add Azure to brand options for console
  operator/v1/types_console.go
Labels: approved, lgtm, size/XS

#247 features: rename features to FeatureGate
  config/v1/register.go
  config/v1/types_feature.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#252 operator/ingress: default Libvirt to HostNetwork
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#249 Add pattern check for ConsoleAuthentication
  config/v1/types_console.go
Labels: approved, lgtm, size/XS

#254 operator/v1: mark all status fields omitempty and optional
  operator/v1/types.go
Labels: approved, lgtm, size/S

#218 Add default project nodeselector
  config/v1/types_scheduling.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#255 Bug 1689061: Add BuildPodEvicted Status Reason
  build/v1/consts.go
Labels: approved, lgtm, size/XS

#251 operator/ingress: change default publishing strategy for unknown platforms
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#221 Added Cluster DNS operator/v1 api
  operator/v1/register.go
  operator/v1/types_dns.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#258 config: remove unused top-level admissionPluginConfig
  config/v1/types.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#259 Remove Local storage from disabled features
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#253 supportpodpidslimit in features
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#256 [3.11] Bug 1690066: Add BuildPodEvicted Status Reason
  build/v1/consts.go
Labels: approved, lgtm, size/XS

#264 operator/v1: fix amangementState regex
  operator/v1/types.go
Labels: approved, lgtm, size/XS

#265 Update OAuth API
  config/v1/types_oauth.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#245 config: InfrastructureSpec reference cloud provider configuration
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#263 Use OperatorCondition instead of custom DNSCondition.
  operator/v1/types_dns.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#267 quota: make namespaces and labelselector optional and nullable
  quota/v1/generated.proto
  quota/v1/types.go
Labels: approved, lgtm, size/XS

#250 Add route.spec.subdomain to support implicit hostnames
  route/v1/generated.pb.go
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#266 Add InfrastructureName.
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M
