Repository openshift/api, pull requests merged in 2019-01, with the labels that each got.

#126 include a generated externalregistryhostname field
  kubecontrolplane/v1/types.go
  kubecontrolplane/v1/types_swagger_doc_generated.go
  kubecontrolplane/v1/zz_generated.deepcopy.go
  openshiftcontrolplane/v1/types.go
  openshiftcontrolplane/v1/types_swagger_doc_generated.go
  openshiftcontrolplane/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#152 Remove embedded TypeMeta from GenericControllerConfig
  config/v1/register.go
  config/v1/types.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#155 tighten build proxy configuration
  config/v1/types_build.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#153 Update ClusterVersion with a desired field and a history field
  config/v1/types_cluster_version.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#149 Rename Infrastructure.CloudProvider to Platform
  config/v1/types_infrastructure.go
Labels: approved, lgtm, size/M

#158 Fix the ConfigMapReference key json
  config/v1/types.go
  config/v1/types_swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#157 Swagger gen should generate types*.go, not just types.go
  .gitattributes
  apps/v1/zz_generated.swagger_doc_generated.go
  authorization/v1/zz_generated.swagger_doc_generated.go
  build/v1/zz_generated.swagger_doc_generated.go
  config/v1/types_swagger_doc_generated.go
  config/v1/zz_generated.swagger_doc_generated.go
  hack/update-swagger-docs.sh
  hack/verify-swagger-docs.sh
  image/v1/zz_generated.swagger_doc_generated.go
  kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  legacyconfig/v1/zz_generated.swagger_doc_generated.go
  network/v1/zz_generated.swagger_doc_generated.go
  oauth/v1/zz_generated.swagger_doc_generated.go
  openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  operator/v1/zz_generated.swagger_doc_generated.go
  operator/v1alpha1/zz_generated.swagger_doc_generated.go
  project/v1/zz_generated.swagger_doc_generated.go
  quota/v1/zz_generated.swagger_doc_generated.go
  route/v1/zz_generated.swagger_doc_generated.go
  security/v1/zz_generated.swagger_doc_generated.go
  servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
  template/v1/zz_generated.swagger_doc_generated.go
  tools/genswaggertypedocs/swagger_type_docs.go
  user/v1/zz_generated.swagger_doc_generated.go
  webconsole/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XXL

#156 add global proxy configuration
  config/v1/register.go
  config/v1/types_build.go
  config/v1/types_proxy.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#150 Update OAuth and Authentication top level configs
  config/v1/register.go
  config/v1/types.go
  config/v1/types_authentication.go
  config/v1/types_build.go
  config/v1/types_idp.go
  config/v1/types_image.go
  config/v1/types_oauth.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#163 add option to enable oapi if needed
  openshiftcontrolplane/v1/types.go
  openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#160 remove detailed logging options
  operator/v1/types.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#164 add coarse grained logging desires to operator API
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#138 add coarse grained logging desires to operator API
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#168 switch build ca ref to configmap ref only (no key)
  config/v1/types_build.go
Labels: approved, lgtm, size/XS

#166 switch build nodeselector config to use map[string]string
  config/v1/types_build.go
  config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#169 switch image ca ref to configmap ref only (no key)
  config/v1/types_image.go
Labels: approved, lgtm, size/XS

#172 config: add project config api
  config/v1/types_project.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#173 project: remove pointer from project request template ref
  config/v1/types_project.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#171 Add StaticPodOperatorSpec to operator/v1
  operator/v1/types.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#174 add types for controlplane operators
  operator/v1/register.go
  operator/v1/types_kubeapiserver.go
  operator/v1/types_kubecontrollermanager.go
  operator/v1/types_openshiftapiserver.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#176 update the clusteroperator version
  config/v1/types_cluster_operator.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#180 require operator version reported
  config/v1/types_cluster_operator.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#177 Remove useUsernameIdentity from KeystoneIdentityProvider
  config/v1/types_oauth.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#175 clusterversion: Rename 'Payload' to 'Image'
  config/v1/types_cluster_version.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#181 Add scheduler api
  config/v1/types_scheduling.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#178 add APIServer config type
  config/v1/register.go
  config/v1/types_apiserver.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#185 clusterversion: Change to status.observedGeneration to be consistent
  config/v1/types_cluster_version.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#159 Update the Console global config struct
  config/v1/types_console.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#187 move annotation constants into api
  annotations/annotations.go
Labels: approved, lgtm, size/S

#183 add types for openshift controller manager operator
  operator/v1/register.go
  operator/v1/types_openshiftcontrollermanager.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#182 infra: Add more constants for platforms and update godoc
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#189 config/v1: add `etcd discovery domain` and `apiserver url` to Infrastructure status.
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#190 migrate console operator config
  operator/v1/register.go
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#191 add etcd operator type
  operator/v1/register.go
  operator/v1/types_etcd.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M
