Repository openshift/api, pull requests merged in 2019-04, with the labels that each got.

#275 Revert "Add route.spec.subdomain to support implicit hostnames"
  route/v1/generated.pb.go
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: approved, size/S

#277 fix route/OWNERS
  route/OWNERS
Labels: approved, lgtm, size/XS

#269 operator/ingress: add tolerations
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#279 add log level for operator
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#278 Enable BlockVolume support tech preview for 4.1
  config/v1/types_feature.go
Labels: approved, lgtm, ok-to-test, size/XS

#274 Add "BareMetal" platform type.
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#276 bug 1683055: Add spec and status comments/description for serviceca operator type
  operator/v1/types_serviceca.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#285 simplify operatorspec to match what we ended up needing
  operator/v1/types.go
  operator/v1/types_kubeapiserver.go
  operator/v1/types_kubecontrollermanager.go
  operator/v1/types_scheduler.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#283 add nullable fields for RoleBindingRestriction
  authorization/v1/generated.proto
  authorization/v1/types.go
Labels: approved, lgtm, size/XS

#281 Switch openshift/api to go1.11
  .travis.yml
  apps/v1/zz_generated.swagger_doc_generated.go
  build/v1/zz_generated.swagger_doc_generated.go
  config/v1/types_feature.go
  config/v1/types_scheduling.go
  config/v1/zz_generated.swagger_doc_generated.go
  image/v1/zz_generated.swagger_doc_generated.go
  legacyconfig/v1/zz_generated.swagger_doc_generated.go
  openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  operator/v1/types_authentication.go
  operator/v1/types_console.go
  operator/v1/types_etcd.go
  operator/v1/types_openshiftapiserver.go
  operator/v1/types_openshiftcontrollermanager.go
  operator/v1/types_serviceca.go
  operator/v1/types_servicecatalogapiserver.go
  operator/v1/zz_generated.swagger_doc_generated.go
  operator/v1alpha1/zz_generated.swagger_doc_generated.go
  security/v1/zz_generated.swagger_doc_generated.go
  webconsole/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#287 Change the ClusterStatusConditionType "Failing" to "Degraded"
  config/v1/types_cluster_operator.go
Labels: approved, lgtm, size/XS

#286 introduce degraded condition
  config/v1/types_cluster_version.go
  config/v1/zz_generated.swagger_doc_generated.go
  operator/v1/types.go
Labels: approved, lgtm, size/XS

#248 makefile: add generator using a container
  Dockerfile.build
  Makefile
Labels: approved, lgtm, size/S

#282 Remove unnecessary scheduling features
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#289 add nullable tags to SCCs
  security/v1/generated.proto
  security/v1/types.go
Labels: approved, lgtm, size/XS

#288 Remove OperatorStatusTypeFailing entirely
  Makefile
  operator/v1/types.go
Labels: approved, lgtm, size/XS

#290 Enable taint nodes by condition
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#292 get back to working feature list
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#291 Restore "Add route.spec.subdomain to support implicit hostnames""
  route/v1/generated.pb.go
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#293 Update ClusterVersion to have a 'force' update flag and track verified
  config/v1/types_cluster_version.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#297 ForceRedeploymentReason is now duplicated, causes openapi failure
  operator/v1/types_etcd.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#296 fix order of comments in serviceca operator type
  operator/v1/types_serviceca.go
Labels: approved, lgtm, size/XS

#295 Add nullable tags for SCCs, take 2
  security/v1/generated.proto
  security/v1/types.go
Labels: approved, lgtm, size/XS

#294 network: add 'Namespace' field for AdditionalNetworks
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS
