Repository openshift/api, pull requests merged in 2019-07, with the labels that each got.

#359 config/v1: add platform status for Azure, GCP
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#314 Add Ovirt platform type
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, ok-to-test, size/XS

#364 Set Operator API to default Optional
  operator/v1/doc.go
Labels: approved, lgtm, size/XS

#361 config: Add ExtraCORSAllowedOrigins to APIServer type
  config/v1/types_apiserver.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#367 APIServer: fix first-letter case of AdditionalCORSAllowedOrigins
  config/v1/types_apiserver.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/XS

#368 Add EU based owners
  OWNERS
Labels: approved, lgtm, size/XS

#363 Add ProxyArgumentList type for ProxyConfig to fix CRD generator
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#366 Make master nodes schedulable
  config/v1/types_scheduling.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#360 Add 'section' property to ConsoleLinkSpec
  console/v1/types_console_link.go
  console/v1/zz_generated.deepcopy.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#372 Bug 1720770: remove broken default serving cert setting
  config/v1/types_apiserver.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#376 Update old +required tags with +kubebuilder:validation:Required
  config/v1/types_apiserver.go
  config/v1/types_authentication.go
  config/v1/types_build.go
  config/v1/types_cluster_operator.go
  config/v1/types_cluster_version.go
  config/v1/types_console.go
  config/v1/types_dns.go
  config/v1/types_feature.go
  config/v1/types_image.go
  config/v1/types_infrastructure.go
  config/v1/types_ingress.go
  config/v1/types_network.go
  config/v1/types_oauth.go
  config/v1/types_project.go
  config/v1/types_proxy.go
  config/v1/types_scheduling.go
  operator/v1/types.go
  operator/v1/types_authentication.go
  operator/v1/types_console.go
  operator/v1/types_etcd.go
  operator/v1/types_kubeapiserver.go
  operator/v1/types_kubecontrollermanager.go
  operator/v1/types_openshiftapiserver.go
  operator/v1/types_openshiftcontrollermanager.go
  operator/v1/types_scheduler.go
  operator/v1/types_serviceca.go
  operator/v1/types_servicecatalogapiserver.go
  operator/v1/types_servicecatalogcontrollermanager.go
  operator/v1alpha1/types_image_content_source_policy.go
Labels: approved, lgtm, size/M

#365 Remove CSIBlockVolume from tech preview in 4.2
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#370 allow a custom set of feature gates to be specified
  config/v1/types_feature.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#348 Add BareMetal status for BareMetal platform
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#373 Add ReadinessEndpoints to Proxy API
  config/v1/types_proxy.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#379 add project annotation API
  project/v1/types.go
Labels: approved, lgtm, size/XS

#321 SimpleMacvlan support in network-operator
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#374 config/v1: add platform status for OpenStack
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#383 Make ProjectRequestMessage optional
  config/v1/types_project.go
Labels: approved, lgtm, size/XS

#382 Make imageURL property of console link optional
  console/v1/types_console_link.go
Labels: approved, lgtm, size/XS

#380 Add ConsoleExternalLogLink type
  console/v1/register.go
  console/v1/types_console_external_log_links.go
  console/v1/zz_generated.deepcopy.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#357 operator/network: add EnableUnidling flag.
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#385 Update NamespaceFilter description in the ConsoleExternalLogLink
  console/v1/types_console_external_log_links.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#384 Modify ImageContentSourcePolicy to distinguish between sources (pull specs) and mirrors
  operator/v1alpha1/types_image_content_source_policy.go
  operator/v1alpha1/zz_generated.deepcopy.go
  operator/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#377 Add Trusted CA to Proxy API type
  config/v1/types_proxy.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#386 config/v1: improve APIServer description
  Makefile
  config/v1/types_apiserver.go
  config/v1/types_authentication.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#387 Bug 1732145: Improve console config resource description
  config/v1/types_console.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#389 Bug 1729310: config/dns: clarify immutable status of DNS configuration
  config/v1/types_dns.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#392 Set Authentication.config spec to optional
  config/v1/types_authentication.go
Labels: approved, lgtm, size/XS

#394 Make Secret/ConfigNameReference.name required
  config/v1/types.go
Labels: approved, lgtm, size/XS

#390 Make config/v1 package default to optional in kubebuilder
  config/v1/doc.go
Labels: approved, lgtm, size/XS

#395 Make authorization/v1 package default to optional in kubebuilder
  authorization/v1/doc.go
Labels: approved, lgtm, size/XS

#391 Bug 1732146: docs/config: clean up
  config/v1/types_dns.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
