Repository openshift/api, pull requests merged in 2019-10, with the labels that each got.

#452 add cipher profiles for external servers
  config/v1/types_apiserver.go
  config/v1/types_feature.go
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#455 operator/dns: fix openapi spec for required fields
  operator/v1/types_dns.go
Labels: approved, lgtm, size/XS

#436 OVN - add geneve port assignment
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#458 update cipher profiles to respect Go/Kube options
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#457 Fix missing validation patterns for console extension CRD objects
  console/v1/types.go
  console/v1/types_console_cli_download.go
  console/v1/types_console_external_log_links.go
  console/v1/types_console_link.go
  console/v1/types_console_notification.go
  console/v1/zz_generated.deepcopy.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#454 operator/ingress: introduce tlsSecurityProfile field
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#451 Add oVirt platform status
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#466 Add `resourceNamespaceUID` variable replacement to `ConsoleExternalLogLink`
  console/v1/types_console_external_log_links.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#463 config/v1: add networkResourceGroupName for azure platform
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#468 kubebuilder tag needs to be on the type itself
  console/v1/types_console_link.go
  console/v1/types_console_notification.go
Labels: approved, lgtm, size/XS

#467 featuregates: Disable legacy node role exclusion for masters
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#462 Bug 1758434: re-enable LocalStorageCapacityIsolation
  config/v1/types_feature.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#378 Add a link to baremetal networking architecture.
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#460 operator/ingress: Fix upstream service docs URL
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#319 Remove webconsole 3.x config
  hack/lib/init.sh
  hack/update-deepcopy.sh
  install.go
  webconsole/install.go
  webconsole/v1/doc.go
  webconsole/v1/register.go
  webconsole/v1/types.go
  webconsole/v1/zz_generated.deepcopy.go
  webconsole/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#465 Add ConsoleYAMLSample CRD type
  console/v1/register.go
  console/v1/types_console_yaml_sample.go
  console/v1/zz_generated.deepcopy.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#471 Update OWNERS
  authorization/OWNERS
  oauth/OWNERS
  project/OWNERS
  security/OWNERS
  user/OWNERS
Labels: approved, lgtm, size/XS

#472 NE-150: operator/ingress: Add observedGeneration
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#473 add operator config for kube-storage-version-migrator operator
  operator/v1/register.go
  operator/v1/types_kubestorageversionmigrator.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#476 tlssecurityprofile: modify tls version strings, remove ECDHE-RSA-AES256-SHA384
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#479 Generate consoleyamlsamples.console.openshift.io CRD
  console/v1/0000_10_config-operator_01_consoleyamlsample.crd.yaml
Labels: approved, lgtm, size/M

#464 Fixed a typo 'addressed -> addresses'
  network/v1/generated.proto
  network/v1/types.go
  network/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#484 Add check to verify no metadata descriptions in CRDs
  Makefile
  hack/verify-crds.sh
Labels: approved, lgtm, size/S

#481 Rename console extension CRDs
  console/v1/0000_10_consoleclidownload.crd.yaml
  console/v1/0000_10_consoleexternalloglink.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/0000_10_consoleyamlsample.crd.yaml
Labels: approved, lgtm, size/XS

#449 API additions required for windows linux hybrid clusters
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#475 Add operator crds
  Makefile
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml-merge-patch
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml-merge-patch
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml-merge-patch
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_service-ca-operator_02_crd.yaml
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
Labels: approved, lgtm, size/XXL

#485 Bug 1764224: Update ConsoleCLIDownloads Href validation regexp
  console/v1/0000_10_consoleclidownload.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/types.go
  console/v1/types_console_cli_download.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#487 operator/ingress: add IngressController CRD
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
Labels: approved, lgtm, size/XL

#489 operator/v1: add latestAvailableRevision to OpenShiftAPIServerStatus
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/types_openshiftapiserver.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#490 Add missing preserveUnknownField marker for pruning
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
Labels: approved, lgtm, size/XS

#491 Add check in hack/verify-crds that pruning is enabled
  console/v1/0000_10_consoleyamlsample.crd.yaml
  hack/verify-crds.sh
Labels: approved, lgtm, size/S

#486 Add console-operator CRD and generate from types
  operator/v1/0000_70_console-operator.crd.yaml
Labels: approved, lgtm, size/L

#488 operator/ingress: Only TLS 1.1 or 1.2 can be used
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#492 Add validation patterns to console-operator structs
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
Labels: approved, lgtm, size/XS

#496 Fix preserveUnknownField typo
  authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  config/v1/0000_03_config-operator_01_proxy.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/0000_10_config-operator_01_build.crd.yaml
  config/v1/0000_10_config-operator_01_console.crd.yaml
  config/v1/0000_10_config-operator_01_dns.crd.yaml
  config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  config/v1/0000_10_config-operator_01_image.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/0000_10_config-operator_01_network.crd.yaml
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/0000_10_config-operator_01_project.crd.yaml
  config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  console/v1/0000_10_consoleclidownload.crd.yaml
  console/v1/0000_10_consoleexternalloglink.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/0000_10_consoleyamlsample.crd.yaml
  hack/verify-crds.sh
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/0000_50_service-ca-operator_02_crd.yaml
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  security/v1/0000_03_security-openshift_01_scc.crd.yaml
Labels: approved, lgtm, size/M

#493 Bring back cipher suites removed earlier
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.swagger_doc_generated.go
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
Labels: approved, lgtm, size/M

#495 config/v1: add clusterversions CRD from CVO
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: approved, lgtm, size/L

#497 config/v1: move ClusterOperator CRD from CVO
  config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_operator.go
Labels: approved, lgtm, size/L

#498 Fix error in hack/verify-crds to check preserveUnknownFields
  hack/verify-crds.sh
Labels: approved, lgtm, size/XS

#503 add KubeStorageVersionMigrator crd.yaml
  operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
Labels: approved, lgtm, size/L

#474 Add label selector to namespace-scoped links
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/types_console_link.go
  console/v1/zz_generated.deepcopy.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#505 Fix PreserveUnknownFields tags and x-kubernetes-int-or-string
  authorization/v1/generated.proto
  authorization/v1/types.go
  config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/v1/types.go
  config/v1/types_cluster_operator.go
  image/v1/generated.proto
  image/v1/types.go
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_service-ca-operator_02_crd.yaml
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types.go
  osin/v1/types.go
  quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml-merge-patch
  servicecertsigner/v1alpha1/types.go
  template/v1/generated.proto
  template/v1/types.go
Labels: approved, lgtm, size/M

#483 Add useful Kuryr settings
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M
