Repository openshift/api, pull requests merged in 2019-12, with the labels that each got.

#524 image: Improve godoc for image types
  image/v1/generated.proto
  image/v1/types.go
  image/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#511 Bug 1773682: Add missing optional tags
  apps/v1/generated.proto
  apps/v1/types.go
  authorization/v1/generated.proto
  authorization/v1/types.go
  authorization/v1/zz_generated.swagger_doc_generated.go
  build/v1/generated.proto
  build/v1/types.go
  route/v1/generated.proto
  route/v1/types.go
  template/v1/generated.proto
  template/v1/types.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#537 Bug 1769008: Adding missing Azure container name validation.
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/types.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#506 service ca: Remove controller-specific configuration
  servicecertsigner/v1alpha1/register.go
  servicecertsigner/v1alpha1/types.go
  servicecertsigner/v1alpha1/zz_generated.deepcopy.go
  servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#532 add conditions to build api
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.deepcopy.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#543 Make {image,project}/v1 status fields optional
  image/v1/generated.proto
  image/v1/types.go
  project/v1/generated.proto
  project/v1/types.go
Labels: approved, lgtm, size/XS

#546 Bug 1769008: Add missing preserveUnknownFields tags
  hack/verify-crds.sh
  imageregistry/v1/00-crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#551 Drop library-go dependency
  go.mod
  go.sum
  hack/alpha-build-machinery/doc.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/tmp.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/build.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/help.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/yq.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/scripts/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/scripts/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#550 Allow sctp protocol with LatencySensitive FG
  config/v1/types_feature.go
Labels: approved, lgtm, size/XS

#553 Fix replace for go mod
  go.mod
  vendor/modules.txt
Labels: approved, lgtm, size/S

#554 Bug 1785419: Allow sctp protocol with LatencySensitive FG
  config/v1/types_feature.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#556 Fix protobuf generation
  hack/update-protobuf.sh
  third_party/protobuf/google/protobuf/descriptor.proto
Labels: approved, lgtm, size/XL

#552 prevent mismatched featuregates
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: approved, lgtm, size/L
