Repository openshift/api, pull requests merged in 2019-08, with the labels that each got.

#388 config/v1: Introduce operatorhub API
  config/v1/register.go
  config/v1/types_operatorhub.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#400 Updates Proxy TrustedCA godocs
  config/v1/types_proxy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#399 Bug 1732150: Update Scheduler config description
  config/v1/types_scheduling.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#405 config/v1: operatorhub API improvements
  config/v1/types_operatorhub.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#408 Updates godocs for trustedCA field of proxy api type
  config/v1/types_proxy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#409 config/v1: add disable all option to operatorhub API
  config/v1/types_operatorhub.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#402 Bug 1738401: config/ingress: clean up docs
  config/v1/types_ingress.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#406 Bug 1732144: Fix description of cluster build config
  apps/v1/generated.pb.go
  authorization/v1/generated.pb.go
  build/v1/generated.pb.go
  config/v1/types_build.go
  config/v1/zz_generated.swagger_doc_generated.go
  image/v1/generated.pb.go
  network/v1/generated.pb.go
  oauth/v1/generated.pb.go
  project/v1/generated.pb.go
  quota/v1/generated.pb.go
  route/v1/generated.pb.go
  security/v1/generated.pb.go
  template/v1/generated.pb.go
  user/v1/generated.pb.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#401 Bug 1743302: Add KuryrConfig.OpenStackServiceNetwork for CNO
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#381 Updating the explanation for Network type
  config/v1/types_network.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S
