Repository openshift/api, pull requests merged in 2020-03, with the labels that each got.

#571 update platform status with ibmcloud
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, ok-to-test, size/S

#591 DEVEXP-544: Add Affinity to the image registry CRD
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#595 Add OmitEmpty to all optional fields
  imageregistry/v1/types.go
Labels: approved, lgtm, size/M

#592 Bug 1811695: Add missing optional tags
  apps/v1/generated.pb.go
  apps/v1/generated.proto
  apps/v1/types.go
  authorization/v1/generated.pb.go
  authorization/v1/generated.proto
  authorization/v1/types.go
  authorization/v1/types_swagger_doc_generated.go
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  config/v1/generated.pb.go
  image/v1/generated.pb.go
  image/v1/generated.proto
  image/v1/types.go
  network/v1/generated.pb.go
  network/v1/generated.proto
  network/v1/types.go
  oauth/v1/generated.pb.go
  operator/v1alpha1/generated.pb.go
  project/v1/generated.pb.go
  project/v1/generated.proto
  project/v1/types.go
  quota/v1/generated.pb.go
  quota/v1/generated.proto
  quota/v1/types.go
  route/v1/generated.pb.go
  route/v1/generated.proto
  route/v1/types.go
  security/v1/generated.pb.go
  security/v1/generated.proto
  security/v1/types.go
  servicecertsigner/v1alpha1/generated.pb.go
  template/v1/generated.pb.go
  template/v1/generated.proto
  template/v1/types.go
  user/v1/generated.pb.go
  webconsole/v1/generated.pb.go
Labels: approved, lgtm, size/S

#597 Fixes #545: Fix copyright in LICENSE file
  LICENSE
Labels: approved, lgtm, size/S

#603 Bug 1809861: add build status reasons for fetch image source and manage dockerfile…
  build/v1/consts.go
Labels: approved, bugzilla/valid-bug, lgtm

#602 adds revision support for `authentication` operator
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/types_authentication.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#605 Bug 1816483: fix(codegen): add missing client tag to operatorhub config type
  config/v1/types_operatorhub.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test

#596 remove the service catalog crds
  Dockerfile.build
  go.sum
  operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
  operator/v1/types_servicecatalogapiserver.go
  operator/v1/types_servicecatalogcontrollermanager.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#609 Add omitempty tags to Route resources.
  route/v1/types.go
Labels: approved, lgtm

#610 Bump to k8s 1.18 GA
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#612 operator: add config operator type
  operator/v1/0000_10_config-operator_01_config.crd.yaml
  operator/v1/types_config.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#613 Add VirtualHostedStyle to S3 configuration options
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#607 Adds wildcardPolicy field to IngressController API
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#615 Update optional tags where needed
  authorization/v1/generated.proto
  authorization/v1/types.go
  build/v1/generated.proto
  build/v1/types.go
Labels: approved, lgtm

#594 Add Route for consoles custom hostname
  config/v1/types_console.go
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S
