Repository openshift/api, pull requests merged in 2020-01, with the labels that each got.

#533 operator/ingress: Add NodePort publishing strategy
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#555 Adding imagepruner api definitions
  imageregistry/v1/01-crd.yaml
  imageregistry/v1/register.go
  imageregistry/v1/types_imagepruner.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#558 feature: Enable the IPv6DualStack feature gate by default
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: approved, lgtm, size/XS

#560 Add rolloutStategy parameter to ImageRegistrySpec
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#561 adding subresources/status to imagepruner crd
  imageregistry/v1/01-crd.yaml
Labels: approved, lgtm, size/XS

#562 Included CSISnapshotController API Type
  Dockerfile.build
  go.mod
  go.sum
  operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  operator/v1/register.go
  operator/v1/types_csi_snapshot.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#563 Fix image registry's rollout parameter
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/types.go
  operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
Labels: approved, lgtm, size/S

#559 operator/ingress: add route admission policy API
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#523 image: Add the ImageTag type to return more details than ImageStreamTag
  image/v1/generated.pb.go
  image/v1/generated.proto
  image/v1/register.go
  image/v1/types.go
  image/v1/zz_generated.deepcopy.go
  image/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#565 operator/ingress: remove routeAdmission from status
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#567 adds a new ManagingOAuthAPIServer field to authentication's operator status field
  go.mod
  go.sum
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/types_authentication.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#541 Add vSphere platform status
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#566 operator/ingress: Fix route admission godoc typos
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XS

#557 create the IBMCLoudPlatform type for the ingress operator try2
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, ok-to-test, size/M

#570 Clarify image config doc
  config/v1/0000_10_config-operator_01_image.crd.yaml
  config/v1/types_image.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#569 Enable overriding service account issuer for bound tokens
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/types_authentication.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#527 Bug 1769015: Add kubebuilder annotations to the network types
  Makefile
  network/v1/001-clusternetwork-crd.yaml
  network/v1/002-hostsubnet-crd.yaml
  network/v1/003-netnamespace-crd.yaml
  network/v1/004-egressnetworkpolicy-crd.yaml
  network/v1/generated.pb.go
  network/v1/generated.proto
  network/v1/types.go
  network/v1/zz_generated.deepcopy.go
  network/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#574 Bug 1785289: add deprecaction notice for build pipeline strategy
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#582 Bug 1797107: config/v1/types_proxy: Clarify trustedCA semantics
  config/v1/0000_03_config-operator_01_proxy.crd.yaml
  config/v1/0000_10_config-operator_01_build.crd.yaml
  config/v1/types_proxy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
