Repository openshift/api, pull requests merged in 2020-12, with the labels that each got.

#796 Add missing optional for BuildSourceType, BuildStrategyType and Identities
  apps/v1/generated.proto
  apps/v1/types.go
  build/v1/generated.proto
  build/v1/types.go
  user/v1/generated.proto
  user/v1/types.go
Labels: approved, lgtm

#794 types_network: Change API that enables IPsec
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#677 Add Scheduler profiles field
  config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  config/v1/types_scheduling.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#793 operator/ingress: Add HTTP header name case adjust
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#801 Remove uniqueItems validation from containerRuntimeSearchRegistries
  config/v1/0000_10_config-operator_01_image.crd.yaml
  config/v1/types_image.go
Labels: approved, lgtm

#804 config/v1/scheduling: fix typo in HighNodeUtililzation
  config/v1/types_scheduling.go
Labels: approved, lgtm

#805 config/v1/scheduling: fix typo in HighNodeUtililzation
  config/v1/types_scheduling.go
Labels: approved, lgtm

#806 Bump schedulers.config.openshift.io CRD to v1
  config/v1/0000_10_config-operator_01_scheduler.crd.yaml
Labels: approved, lgtm

#809 Bump CRDs to apiextensions.k8s.io/v1
  authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  config/v1/0000_03_config-operator_01_proxy.crd.yaml
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/0000_10_config-operator_01_project.crd.yaml
  config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  security/v1/0000_03_security-openshift_01_scc.crd.yaml
Labels: approved, lgtm

#763 Add option to define (and customize) console catalog categories
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#811 Fix additionalPrinterColumns CRDs
  network/v1/001-clusternetwork-crd.yaml
  network/v1/002-hostsubnet-crd.yaml
  network/v1/003-netnamespace-crd.yaml
  security/v1/0000_03_security-openshift_01_scc.crd.yaml
Labels: approved, lgtm

#815 Bug 1905328: Add warning of the consequences of changing bound token issuer
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/types_authentication.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#825 Bug 1907373: bring selflinks back for 4.7, they will be removed in 4.8
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
