Repository openshift/api, pull requests merged in 2020-05, with the labels that each got.

#642 Bug 1788848: oc explain apiservers.spec gets empty DESCRIPTION
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/types_apiserver.go
  config/v1/types_oauth.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#648 Bug 1784151: set additionalPrinterColumns for SCC
  security/v1/0000_03_security-openshift_01_scc.crd.yaml
  security/v1/generated.proto
  security/v1/types.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#651 Bug 1826230: Bump to kube 1.18.3
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#652 Bug 1774616: BuildLogOptions has drifted from PodLogOptions
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#644 Bug 1809354: operatoringress/dnsrecord: Add observedGeneration
  operatoringress/v1/0000_50_dns-record.yaml
  operatoringress/v1/types.go
  operatoringress/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#649 Bug 1835004: Add keepYoungerThanDuration and deprecate keepYoungerThan
  Makefile
  go.mod
  hack/typelinter/typelinter.go
  hack/verify-types.sh
  imageregistry/v1/01-crd.yaml
  imageregistry/v1/types_imagepruner.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/gcexportdata/importer.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/exportdata.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/newInterface10.go
  vendor/golang.org/x/tools/go/internal/gcimporter/newInterface11.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
