Repository openshift/api, pull requests merged in 2020-09, with the labels that each got.

#732 Bug 1874613: operator/v1: fix scope of ingresscontrollers to be namespaced
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#737 Bug 1879073: Add omitempty to logging
  imageregistry/v1/types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#739 Bug 1879592: Add logLevel to imagepruners.imageregistry.operator.openshift.io
  imageregistry/v1/01-crd.yaml
  imageregistry/v1/types_imagepruner.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#733 [release-4.5] Bug 1843244: Adding documentation for Logging field
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#741 Bug 1880786: operatorcontrolplane: make structural
  operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#746 Bug 1878163: Update vendoring for golang 1.15
  go.mod
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#735 Bug 1877487: add valid values for ConsoleNotification location
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/types_console_notification.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#742 Bug 1873043: bring back service-ca crd names
  operator/v1/0000_50_service-ca-operator_02_crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#736 Bug 1878040: Validations for LogLevel fields
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/01-crd.yaml
  operator/v1/0000_10_config-operator_01_config.crd.yaml
  operator/v1/0000_20_etcd-operator_01.crd.yaml
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  operator/v1/0000_50_service-ca-operator_02_crd.yaml
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#752 Bug 1878040: operator: rename etcd CRD to name from repo
  operator/v1/0000_12_etcd-operator_01_config.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#753 Bug 1878040: operator: allow log levels for old clients and unify OperatorLogLevel
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/01-crd.yaml
  operator/v1/0000_10_config-operator_01_config.crd.yaml
  operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  operator/v1/0000_50_service-ca-operator_02_crd.yaml
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#755 Bug 1883603: podnetworkconnectivitychecks.controlplane.operator.openshift.io is invalid
  operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#751 Bug 1883458: add CRD based internal rangeallocations for SCC uid allocation
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  hack/verify-crds.sh
  securityinternal/install.go
  securityinternal/v1/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml
  securityinternal/v1/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml-patch
  securityinternal/v1/doc.go
  securityinternal/v1/register.go
  securityinternal/v1/types.go
  securityinternal/v1/zz_generated.deepcopy.go
  securityinternal/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#756 Bug 1883701: operator/ingress: Restore scale subresource
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
