Repository openshift/api, pull requests merged in 2020-02, with the labels that each got.

#583 Bug 1784532: Clarify FROM behavior in builds
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
  network/v1/001-clusternetwork-crd.yaml
  network/v1/002-hostsubnet-crd.yaml
  network/v1/003-netnamespace-crd.yaml
  network/v1/004-egressnetworkpolicy-crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#573 Bug 1798482: Add CRD generator documentation to Readme
  README.md
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#576 Bug 1794804: Remove Description from CLI output to improve its display
  console/v1/0000_10_consoleclidownload.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#585 Bug 1794376: config: disable IPv6DualStack feature flag
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#589 Bug 1801543: Add missing enum validations
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/types_tlssecurityprofile.go
  operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  operator/v1/types_ingress.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#584 Bug 1770677: operator/ingress: add dnsrecord type
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  operatoringress/install.go
  operatoringress/v1/0000_50_dns-record.yaml
  operatoringress/v1/doc.go
  operatoringress/v1/register.go
  operatoringress/v1/types.go
  operatoringress/v1/zz_generated.deepcopy.go
  operatoringress/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#577 Bug 1774156: 4.2 cherry-picks in support of automated service ca rotation
  servicecertsigner/v1alpha1/types.go
  servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
