Repository openshift/api, pull requests merged in 2021-12, with the labels that each got.

#1075 Create a feature gate for MAPO tech preview
  config/v1/types_feature.go
Labels: lgtm, approved

#1054 [OCPCLOUD-1303] Add API to support Worker nodes with Ephemeral OS disks on Azure
  machine/v1beta1/types_azureprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1077 Add .ci-operator.yaml
  .ci-operator.yaml
  hack/verify-crds.sh
Labels: lgtm, approved

#1079 Adding updates from update-gofmt for go1.17
  apiserver/v1/zz_generated.deepcopy.go
  apps/v1/zz_generated.deepcopy.go
  authorization/v1/zz_generated.deepcopy.go
  build/v1/zz_generated.deepcopy.go
  cloudnetwork/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.deepcopy.go
  console/v1/zz_generated.deepcopy.go
  console/v1alpha1/zz_generated.deepcopy.go
  dependencymagnet/doc.go
  helm/v1beta1/zz_generated.deepcopy.go
  image/docker10/zz_generated.deepcopy.go
  image/dockerpre012/zz_generated.deepcopy.go
  image/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.deepcopy.go
  kubecontrolplane/v1/zz_generated.deepcopy.go
  legacyconfig/v1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.deepcopy.go
  network/v1/zz_generated.deepcopy.go
  networkoperator/v1/zz_generated.deepcopy.go
  oauth/v1/zz_generated.deepcopy.go
  openshiftcontrolplane/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1alpha1/zz_generated.deepcopy.go
  operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  operatoringress/v1/zz_generated.deepcopy.go
  osin/v1/zz_generated.deepcopy.go
  project/v1/zz_generated.deepcopy.go
  quota/v1/zz_generated.deepcopy.go
  route/v1/zz_generated.deepcopy.go
  samples/v1/zz_generated.deepcopy.go
  security/v1/zz_generated.deepcopy.go
  securityinternal/v1/zz_generated.deepcopy.go
  servicecertsigner/v1alpha1/zz_generated.deepcopy.go
  sharedresource/v1alpha1/zz_generated.deepcopy.go
  template/v1/zz_generated.deepcopy.go
  user/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#1078 Add API for MTU migration
  config/v1/0000_10_config-operator_01_network.crd.yaml
  config/v1/types_network.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1033 SDN 2316: Add GatewayConfig to OVNKubernetesConfig
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1061 config/v1: Add NodeSwap to TechPreviewNoUpgrade
  config/v1/types_feature.go
Labels: lgtm, approved

#1045 Machine API: adding Alibaba cloud provider types.
  machine/v1/common.go
  machine/v1/doc.go
  machine/v1/register.go
  machine/v1/types_alibabaprovider.go
Labels: lgtm, approved

#1080 change the `ResourceGroupID` to optional on alibabacloud provider
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
Labels: lgtm, approved, ok-to-test

#1081 Alibaba cloud platform: Readding kubebuilder validation to infrastruc…
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
Labels: lgtm, approved

#1086 Updating build-machinery-go to fix the yaml_patch error
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved

#1082 Alibaba Cloud Provider: introducing imageregistry types
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/00_imageregistry.crd.yaml
  imageregistry/v1/00_imageregistry.crd.yaml-patch
  imageregistry/v1/01_imagepruner.crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1087 Fix rename property patch from type to method
  imageregistry/v1/00_imageregistry.crd.yaml
  imageregistry/v1/00_imageregistry.crd.yaml-patch
  imageregistry/v1/types.go
Labels: lgtm, approved

#1085 Bug 2032289: omit empty fields in ConsolePlugin CR
  console/v1alpha1/types_console_plugin.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1088 Bug 2033536: Alibaba infrastructure config: Updating kube validation on optional s…
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1089 Bug 2034879: Ensure name and owner are required within lifecycle hooks
  machine/v1beta1/0000_10_machine.crd.yaml
  machine/v1beta1/0000_10_machineset.crd.yaml
  machine/v1beta1/types_machine.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
