Repository openshift/api, pull requests merged in 2021-07, with the labels that each got.

#962 Use separate enum validation for control plane and infra topology
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#952 BUILD-159: add projected share resource csi driver operator to the list managed by the CSO
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: approved, lgtm

#941 feat(imageregistry): Support IBMCOS storage type
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#960 config/v1 apiserver: add audit.customRules
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/types_apiserver.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#935 clarify that Progressing should be true when operators/operands react…
  config/v1/types_cluster_operator.go
Labels: approved, lgtm

#966 add field to make service-ca.crt more secure
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/types_kubecontrollermanager.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#969 bump(build-machinery): versioned binaries
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/default.mk
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: approved, lgtm

#927 operator/ingress: Delete outdated godoc re TLSv1.3
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#885 config/v1/types_cluster_version: Update force and verified godocs
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#958 NE-310 Implement route admission support for HSTS header
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/types.go
  config/v1/types_ingress.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#731 operator/ingress: Add client certificate parameters
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#888 operator/dns: Add managementState field to dns operator
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#975 IBM cloud managed profile: add consoleplugin CRD
  console/v1alpha1/0000_10_consoleplugin.crd.yaml
Labels: approved, lgtm

#961 Add ExternalCloudProvider to TechPreviewNoUpgrade FeatureSet
  config/v1/types_feature.go
Labels: approved, lgtm

#977 operator/v1: add ladfailedReason to NodeStatus
  operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#729 operator/ingress: Add parameters for empty requests
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#968 NE-412: operator/ingress: Add options for tuning connection timeouts in openshift ingress controller
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#978 Bug 1985997: operator/v1: clarify nodeStatus.last{failedCount,fallbackCount}
  operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  operator/v1/types.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#980 Bug 1986129: Add missing 'include.release.openshift.io/single-node-developer' annotation to the ConsolePlugin CRD
  console/v1alpha1/0000_10_consoleplugin.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
