Repository openshift/api, pull requests merged in 2021-06, with the labels that each got.

#904 Bug 1951853: operator/dns: Describe default toleration
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#922 Bug 1957822: apiserver.config: add 'Custom' to available TLSSecurityProfiles
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/types_apiserver.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#933 Bug 1956826: add restriction note for docker strategy build args
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#934 Bug 1960101: Fixed port section of kubebuilder validation pattern
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/types_network.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#929 Bug 1947402: Add policyv1 scheme
  install.go
  vendor/k8s.io/api/policy/v1/doc.go
  vendor/k8s.io/api/policy/v1/generated.pb.go
  vendor/k8s.io/api/policy/v1/generated.proto
  vendor/k8s.io/api/policy/v1/register.go
  vendor/k8s.io/api/policy/v1/types.go
  vendor/k8s.io/api/policy/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/policy/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#926 config/v1/types_cluster_operator: Expand upgradeable inputs to cluster scope
  config/v1/types_cluster_operator.go
Labels: approved, lgtm

#860 config: Azure Stack Hub support
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
Labels: approved, lgtm

#919 BUILD-87: secret configmap volume mounts in builds
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.deepcopy.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, qe-approved

#943 removing conversion-gen=false for BuildVolumeSource.Type field
  build/v1/generated.proto
  build/v1/types.go
Labels: approved, lgtm

#946 Add go.mod to tls dir to avoid invalid char errors on vendoring
  tls/go.mod
Labels: approved, lgtm

#942 Clarify that useExternalOpenvswitch is deprecated and ignored
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#938 Bump to controller-gen v0.6.0
  Makefile
  apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  config/v1/0000_03_config-operator_01_proxy.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/0000_10_config-operator_01_build.crd.yaml
  config/v1/0000_10_config-operator_01_console.crd.yaml
  config/v1/0000_10_config-operator_01_dns.crd.yaml
  config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  config/v1/0000_10_config-operator_01_image.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/0000_10_config-operator_01_network.crd.yaml
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/0000_10_config-operator_01_project.crd.yaml
  config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  console/v1/0000_10_consoleclidownload.crd.yaml
  console/v1/0000_10_consoleexternalloglink.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/0000_10_consolequickstart.crd.yaml
  console/v1/0000_10_consoleyamlsample.crd.yaml
  console/v1alpha1/0000_10_consoleplugin.crd.yaml
  helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
  imageregistry/v1/00-crd.yaml
  imageregistry/v1/01-crd.yaml
  network/v1/001-clusternetwork-crd.yaml
  network/v1/002-hostsubnet-crd.yaml
  network/v1/003-netnamespace-crd.yaml
  network/v1/004-egressnetworkpolicy-crd.yaml
  operator/v1/0000_10_config-operator_01_config.crd.yaml
  operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  operator/v1/0000_50_service-ca-operator_02_crd.yaml
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  operator/v1/types_network.go
  operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  operatoringress/v1/0000_50_dns-record.yaml
  quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  samples/v1/0000_10_samplesconfig.crd.yaml
  security/v1/0000_03_security-openshift_01_scc.crd.yaml
Labels: approved, lgtm

#940 Add external topology mode
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#954 BUILD-87: Add support for build volumes
  build/v1/generated.proto
  build/v1/types.go
Labels: approved, lgtm

#953 Add AWS EFS CSI driver
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: approved, lgtm

#951 Add CISInstanceCRN to IBMCloudPlatformStatus
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#949 operatoringress: Fix typo in DNSRecord CRD.
  operatoringress/v1/0000_50_dns-record.yaml
  operatoringress/v1/types.go
  operatoringress/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#957 Add feature gates for tech preview CSI drivers: GCE and Azure
  config/v1/types_feature.go
Labels: approved, lgtm
