Repository openshift/api, pull requests merged in 2021-02, with the labels that each got.

#819 Bug 1905576: [release-4.5] Add warning of the consequences of changing bound token issuer
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/types_authentication.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#838 Fix disgest typo in ICSP api docs
  operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  operator/v1alpha1/types_image_content_source_policy.go
  operator/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/valid-bug, lgtm

#748 dockerfile: use latest fedora for generating CRDs
  Dockerfile.build
Labels: approved, lgtm

#814 Fix typo in ProjectRequest
  project/v1/generated.proto
  project/v1/types.go
  project/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#827 Add HighAvailabilityMode field to 'infrastructure' CRD
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#828 add some docs for the generated CRDs for the cloudcredentials type
  operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  operator/v1/types_cloudcredential.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#841 Update etcd CRD description
  operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  operator/v1/types_etcd.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#784 Add EquinixMetal config api types
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, ok-to-test

#839 Include Azure Disk CSI in CSI Cluster Drivers
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: approved, lgtm

#842 Bug 1901535: Remove the ManagingOAuthAPIServer field from authentication.operator API
  operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  operator/v1/types_authentication.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#836 Add Kubevirt CSI Driver to ClusterCSIDriver's enum
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: approved, lgtm

#826 re-align selflink to kube
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: approved, lgtm

#845 operator/ingress: Add GCP Global Access for LBs
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#831 Bug 1895053: Allow builds to mount the proxy CA
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.deepcopy.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#848 Buildconfig: Document valid values for spec.triggers.type
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm
