Repository openshift/api, pull requests merged in 2021-10, with the labels that each got.

#979 BUILD-284: Relocate shared resources api into openshift/api repository
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  install.go
  sharedresource/OWNERS
  sharedresource/install.go
  sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
  sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
  sharedresource/v1alpha1/doc.go
  sharedresource/v1alpha1/register.go
  sharedresource/v1alpha1/types_shared_configmap.go
  sharedresource/v1alpha1/types_shared_secret.go
  sharedresource/v1alpha1/zz_generated.deepcopy.go
  sharedresource/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1022 AUTH-8: config,oauth: add groups to retrievable OpenIDClaims
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/types_oauth.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  osin/v1/types.go
  osin/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#1026 Update patch merge tags in struct to match those in the comment
  config/v1/types_cluster_version.go
  sharedresource/v1alpha1/types_shared_configmap.go
  sharedresource/v1alpha1/types_shared_secret.go
Labels: lgtm, approved

#1028 Bug 1992592: Atomic List Type
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/types_oauth.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
