Repository openshift/api, pull requests merged in 2021-11, with the labels that each got.

#1047 Bug 2013238: Make the documentation for tls.certificate more verbose
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1020 CONSOLE-2892: Allow dynamic plugins to proxy to services on the cluster
  console/v1alpha1/0000_10_consoleplugin.crd.yaml
  console/v1alpha1/types_console_plugin.go
  console/v1alpha1/zz_generated.deepcopy.go
  console/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved

#1042 config/v1/types_oauth: add OAuthAudit
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/types_oauth.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#976 Bug 1964112: Fix for host name validator error
  route/v1/types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1051 README.md: Add a reference for API conventions
  README.md
Labels: lgtm, approved

#1057 Bug 2023434: Add Purchase Plan Name to Azure Machine Provider Spec
  machine/v1beta1/types_azureprovider.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1044 update types_gcprovider.go
  machine/v1beta1/types_gcpprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1063 add ibmcloud satellite upi provider enum
  config/v1/types_infrastructure.go
Labels: lgtm, approved

#1025 Changes to update Power VS PlatformSpec with ServiceEndpoints
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1070 janitorial: drop repeated words words
  build/v1/consts.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
  config/v1/zz_generated.swagger_doc_generated.go
  image/v1/generated.proto
  image/v1/types.go
  image/v1/zz_generated.swagger_doc_generated.go
  kubecontrolplane/v1/types.go
  kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  legacyconfig/v1/types.go
  legacyconfig/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1073 Revert "config/v1/types_oauth: add OAuthAudit"
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  config/v1/types_oauth.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved
