Repository openshift/api, pull requests merged in 2021-03, with the labels that each got.

#808 Bug 1904523: Add useMultiNetworkPolicy flag to enable multiNetworkPolicy
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#855 BUILD-186: build lastTriggeredImageID needs to be in status
  build/v1/generated.pb.go
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.deepcopy.go
  build/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#852 Update Ingresses.config to support route configuration
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/types_ingress.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#863 Include vSphere CSI Driver in clustercsidrivers
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: approved, lgtm

#846 Add export network flows API options
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#861 Bug 1928931: operator/v1: switch DNSRecord CRD to v1
  operatoringress/v1/0000_50_dns-record.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#812 SCTP is GA, so no longer feature-gated
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: approved, lgtm

#853 [SDN-1364] Update OVN-K config for Audit logging
  operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#854 operator/ingress: Add Ingress Controller Tunable Buffer Sizes
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#867 Bug 1928931: Set spec.scope for DNSRecord CRD
  operatoringress/v1/0000_50_dns-record.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#868 operator/ingress: Fix up Tunable Buffer Sizes API
  operator/v1/types_ingress.go
Labels: approved, lgtm

#865 Drop batch/v2alpha1 which is not being used
  install.go
  vendor/k8s.io/api/batch/v2alpha1/doc.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.proto
  vendor/k8s.io/api/batch/v2alpha1/register.go
  vendor/k8s.io/api/batch/v2alpha1/types.go
  vendor/k8s.io/api/batch/v2alpha1/types_swagger_doc_generated.go
  vendor/k8s.io/api/batch/v2alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#851 Add Egress Router CRD
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  install.go
  networkoperator/OWNERS
  networkoperator/install.go
  networkoperator/v1/001-egressrouter.crd.yaml
  networkoperator/v1/001-egressrouter.crd.yaml-patch
  networkoperator/v1/doc.go
  networkoperator/v1/generated.pb.go
  networkoperator/v1/generated.proto
  networkoperator/v1/register.go
  networkoperator/v1/types_egressrouter.go
  networkoperator/v1/zz_generated.deepcopy.go
  networkoperator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#821 Bug 1908068: Enable DownwardAPIHugePages feature gate
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#871 operator/ingress: Add PROXY protocol API
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#870 operator/dns: Add DNS pod placement API
  operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#877 Add feature gates for tech preview CSI drivers
  config/v1/types_feature.go
Labels: approved, lgtm

#857 Add option to customize project access roles
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm
