Repository openshift/api, pull requests merged in 2022-06, with the labels that each got.

#1191 Bug 2081457: kubebuilder validation format hostname is not RFC compliant
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/types_ingress.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1194 Clarify which labels are needed for merge and who applies them
  README.md
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1204 [OCPCLOUD-1583] Add API for Azure Machine API boot diagnostics configuration
  machine/v1beta1/types_azureprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1154 Bug 2094891: IBMCloud: Add DNS CRN to IBM PlatformStatus
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1071 Update docstrings for VSphereMachineProviderSpec
  machine/v1beta1/types_vsphereprovider.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved
