Repository openshift/api, pull requests merged in 2022-09, with the labels that each got.

#1279 USHIFT-333: route/v1: Fix CRD to allow path for non-TLS routes
  route/v1/route.crd.yaml
  route/v1/route.crd.yaml-patch
  route/v1/test-route-validation.sh
Labels: lgtm, approved, bugzilla/valid-bug

#1245 Insights config API
  config/v1/types_feature.go
  config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
  config/v1alpha1/doc.go
  config/v1alpha1/register.go
  config/v1alpha1/types_insights.go
  config/v1alpha1/zz_generated.deepcopy.go
  config/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1270 Add omitempty to dnsmanagementpolicy
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operatoringress/v1/0000_50_dns-record.yaml
  operatoringress/v1/types.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1203 Bump controller-gen to v0.9.2.
  Makefile
  apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/0000_03_config-operator_01_proxy.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/0000_10_config-operator_01_build.crd.yaml
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/0000_10_config-operator_01_oauth.crd.yaml
  console/v1/0000_10_consoleexternalloglink.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
  helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  imageregistry/v1/00_imageregistry.crd.yaml
  imageregistry/v1/01_imagepruner.crd.yaml
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1beta1/0000_10_machine.crd.yaml
  machine/v1beta1/0000_10_machinehealthcheck.yaml
  machine/v1beta1/0000_10_machineset.crd.yaml
  monitoring/v1alpha1/0000_50_monitoring_01_alertingrules.crd.yaml
  monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/0000_50_insights-operator_00-insightsoperator.crd.yaml
  operator/v1/0000_70_dns-operator_00.crd.yaml
  platform/v1alpha1/platformoperators.crd.yaml
  quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
  sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1275 OCPBUGS-236: Add missing time units to ingresscontroller.spec.tuningOptions.reloadInterval
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1285 update to release.openshift.io/feature-set to match OCP 4.12
  config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
  monitoring/v1alpha1/0000_50_monitoring_01_alertingrules.crd.yaml
  monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  platform/v1alpha1/platformoperators.crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1250 OCPSE-25: introduce EvaluationConditionsDetected ClusterStatusConditionType
  config/v1/types_cluster_operator.go
Labels: lgtm, approved, bugzilla/valid-bug

#1271 STOR 437- Create API for vsphere CSI topology configuration
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/types_csi_cluster_driver.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1293 add demonstration of how to add a TechPreview-only option to an enumeration
  Makefile
  example/v1/0000_50_stabletype-default.crd.yaml
  example/v1/0000_50_stabletype-techpreview.crd.yaml
  example/v1/types_stable.go
  example/v1/zz_generated.deepcopy.go
  example/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, bugzilla/valid-bug

#1296 Do not register idms&itms
  config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1269 ODC-6783: Allow hiding console perspectives
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1302 Drop OpenStack failure domain configuration from ControlPlaneMachineSet
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1/types_controlplanemachineset.go
  machine/v1/zz_generated.deepcopy.go
  machine/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1303 fix InsightsDataGather CRD
  Makefile
  config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1282 platform/v1alpha1: Update the cluster profile annotations
  platform/v1alpha1/platformoperators.crd.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1256 ODC-6778: Add console developer catalog customization
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1307 Add Joel Speed as API approver
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug

#1297 Updates to ControlPlaneMachineSet validation with CEL
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1/Makefile
  machine/v1/control-plane-machine-set.aws.stable.testsuite.yaml
  machine/v1/control-plane-machine-set.azure.stable.testsuite.yaml
  machine/v1/control-plane-machine-set.gcp.stable.testsuite.yaml
  machine/v1/control-plane-machine-set.stable.testsuite.yaml
  machine/v1/types_aws.go
  machine/v1/types_controlplanemachineset.go
  machine/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  tests/hack/test.sh
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1315 NE-1084: Add additional cache ttl time units
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_dns-operator_00.crd.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1310 ODC-6778: fix devcatalog types api issue
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1278 [SPLAT-594] vSphere: add zonal spec to infrastructure object
  Makefile
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml-patch
  config/v1/types_infrastructure.go
  config/v1/types_infrastructure_test.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1222 NE-955: IngressController - Add LoadBalancer AllowedSourceRanges API
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved
