Repository openshift/api, pull requests merged in 2022-04, with the labels that each got.

#1110 Add DNS-over-TLS related types
  operator/v1/0000_70_dns-operator_00.crd.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1160 Revert config/v1/Node CRD yaml
  config/v1/0000_10_config-operator_01_node.crd.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1158 Add Nutanix to the LoadBalancerProviderType enum
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1156 [OCPCLOUD-1436] Api changes for adding IMDSv2 support for AWS machines
  machine/v1beta1/types_awsprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1164 Do not register new ICSP CRDs, yet
  config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1165 config/node: Update status to use metav1.Condition type; Re-add node crd.yaml
  config/v1/0000_10_config-operator_01_node.crd.yaml
  config/v1/types_node.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1172 Bug 2074243: `DefaultPlacement` allow empty enum value and remove default
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/types_ingress.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1175 Allow 0 values for host network IngressControllers
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1166 Change to NutanixMachineProviderConfig to allow to configure one or more subnets for a Machine VM
  machine/v1/types_nutanixprovider.go
  machine/v1/zz_generated.deepcopy.go
  machine/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1176 Add the default port documentation and remove incorrect CA note
  operator/v1/0000_70_dns-operator_00.crd.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1185 config/v1/types_cluster_version: Add KnownClusterVersionCapabilities
  config/v1/types_cluster_version.go
  config/v1/types_cluster_version_test.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1159 Add PowerVSMachineProviderConfig
  machine/v1/types_powervsprovider.go
  machine/v1/zz_generated.deepcopy.go
  machine/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1183 machine: remove aws placement groups
  machine/v1/0000_10_awsplacementgroup.crd.yaml
  machine/v1/register.go
  machine/v1/types.go
  machine/v1/types_awsplacementgroup.go
  machine/v1/zz_generated.deepcopy.go
  machine/v1/zz_generated.swagger_doc_generated.go
  machine/v1beta1/types_awsprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug

#1161 types/ingress: add new tuning option: maxConnections
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-patch
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#730 NE-407: operator/ingress: Add ELB connection idle timeout
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved
