Repository openshift/api, pull requests merged in 2022-08, with the labels that each got.

#1225 NE-586: ingress: add ReloadInterval API field
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1240 config/v1: Change ClusterVersion capability from 'console' to 'Console'
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
  console/v1/0000_10_consoleclidownload.crd.yaml
  console/v1/0000_10_consoleexternalloglink.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/0000_10_consolequickstart.crd.yaml
  console/v1/0000_10_consoleyamlsample.crd.yaml
  console/v1alpha1/0000_10_consoleplugin.crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug

#1213 Add basic authentication configuration support for Project Helm repositories
  helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  helm/v1beta1/types_project_helm_chart_repository.go
  helm/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1231 Add storage capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, approved, docs-approved, px-approved

#1226 Updated generated after bumping protoc
  .ci-operator.yaml
  Dockerfile.build
  Makefile
  authorization/v1/generated.pb.go
  go.mod
  howqq
  tls/go.mod
  vendor/github.com/dave/dst/go.mod
  vendor/github.com/dave/dst/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-openapi/jsonpointer/go.mod
  vendor/github.com/go-openapi/jsonpointer/go.sum
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/json/go.mod
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1200 CFE-555: Add additional fields to configure DNS management on ingresscontrollers
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
  operatoringress/v1/0000_50_dns-record.yaml
  operatoringress/v1/types.go
  operatoringress/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, tide/merge-method-squash, qe-approved, docs-approved, px-approved

#1251 Bring back tls/go.mod file
  Makefile
  tls/go.mod
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1247 [OCPNODE-521]Register ImageDigest/TagMirrorSet CRDs
  config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1214 NE-928: Add DNSCache type and spec field
  operator/v1/0000_70_dns-operator_00.crd.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1252 add openapi generation
  .gitignore
  Makefile
  go.mod
  hack/lib/init.sh
  hack/update-deepcopy.sh
  hack/update-openapi.sh
  hack/verify-openapi.sh
  machine/v1/types_controlplanemachineset.go
  machine/v1/types_powervsprovider.go
  openapi/cmd/models-schema/main.go
  openapi/doc.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, bugzilla/valid-bug

#1254 Add status to ImageDigest/TagMirror API to pass ci
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
  config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  config/v1/types_image_digest_mirror_set.go
  config/v1/types_image_tag_mirror_set.go
  config/v1/zz_generated.swagger_doc_generated.go
  image/v1/types.go
  networkoperator/v1/types_egressrouter.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1255 additional tweaks required to be compatible with applyconfiguration
  hack/update-openapi.sh
  imageregistry/v1/00_imageregistry.crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, bugzilla/valid-bug

#1253 Add feature flags for SDN migration
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1259 Add missing unionDiscriminator tag to NutanixResourceIdentifier
  machine/v1/types_nutanixprovider.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, docs-approved, px-approved

#1260 Drop GA-ed features (CSIMigrationAWS, CSIMigrationGCE, PodSecurity)
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1258 [OCPNODE-1147] : Add cgroups v2 to TechPreviewNoUpgrade FeatureSet
  config/v1/types_feature.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1262 update ingress component route SSA list markers
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/types_ingress.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, bugzilla/valid-bug

#1265 BUG 1843043: Improve the description of the config operator config resource
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_10_config-operator_01_config.crd.yaml
  operator/v1/types_config.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1249 Generate list of group versions for update scripts
  Makefile
  config/v1/zz_generated.deepcopy.go
  hack/lib/init.sh
  hack/update-compatibility.sh
  hack/update-deepcopy.sh
  hack/update-deps.sh
  hack/update-openapi.sh
  hack/update-protobuf.sh
  hack/update-swagger-docs.sh
  hack/verify-compatibility.sh
  hack/verify-crds-version-upgrade.sh
  hack/verify-deepcopy.sh
  hack/verify-protobuf.sh
  hack/verify-swagger-docs.sh
  helm/v1beta1/zz_generated.swagger_doc_generated.go
  image/docker10/types_docker.go
  image/docker10/zz_generated.swagger_doc_generated.go
  image/dockerpre012/types_docker.go
  image/dockerpre012/zz_generated.swagger_doc_generated.go
  image/v1/types.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  osin/v1/zz_generated.swagger_doc_generated.go
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
  unidling/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1267 Fixed lifecycle typo in ingress godoc
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1268 TechPreviewNoUpgrade: add Crun feature to set
  config/v1/types_feature.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1234 feat(platform): introduce Platform API at v1alpha1 level
  Makefile
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  platform/install.go
  platform/v1alpha1/doc.go
  platform/v1alpha1/platformoperators.crd.yaml
  platform/v1alpha1/register.go
  platform/v1alpha1/types.go
  platform/v1alpha1/zz_generated.deepcopy.go
  platform/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1273 Remove CSIMigrationAWS and CSIMigrationGCE feature gate references
  config/v1/types_feature.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1209 LBType field for AWS in infra cluster object.
  config/v1/0000_10_config-operator_01_ingress.crd.yaml
  config/v1/types_ingress.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1263 [CNF-5646] Add CSISnapshot capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved
