Repository openshift/api, pull requests merged in 2022-10, with the labels that each got.

#1211 IR-258: add support for manifest list on ImageStreams
  image/v1/generated.pb.go
  image/v1/generated.proto
  image/v1/types.go
  image/v1/zz_generated.deepcopy.go
  image/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1320 machine/v1alpha1: Expose GroupVersion
  machine/v1alpha1/register.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1316 STOR-829: Add CSIInlineVolumeAdmission feature gate
  config/v1/types_feature.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1313 AUTH-309: operator: add service account issuers to KAS status
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/types_authentication.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/types_kubeapiserver.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, docs-approved, px-approved

#1299 NE-1071: Default HAProxy maxconn value to 50000 for OCP 4.12
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1325 RFE-2797: config/v1: Add MatchLabelKeysInPodTopologySpread to TechPreviewNoUpgrade
  config/v1/types_feature.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1323 OCPBUGS-2163: [release-4.10] operator: add service account issuers into kubernetes apiserver operator
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
  cmd/openshift-compatibility-gen/generate/compatibility/gen_type.go
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/types_authentication.go
  config/v1/types_feature.go
  config/v1/types_infrastructure.go
  config/v1/types_oauth.go
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.swagger_doc_generated.go
  image/v1/types.go
  legacyconfig/v1/types.go
  legacyconfig/v1/zz_generated.swagger_doc_generated.go
  machine/v1/types_alibabaprovider.go
  networkoperator/v1/types_egressrouter.go
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/0000_70_dns-operator_00.crd.yaml
  operator/v1/types_dns.go
  operator/v1/types_ingress.go
  operator/v1/types_kubeapiserver.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
  sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
  sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
  sharedresource/v1alpha1/types_shared_configmap.go
  sharedresource/v1alpha1/types_shared_secret.go
  sharedresource/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#1324 OCPBUGS-2164: [release-4.9] operator: add service account issuers into kubernetes apiserver operator
  build/v1/generated.proto
  build/v1/types.go
  build/v1/zz_generated.swagger_doc_generated.go
  cmd/openshift-compatibility-gen/generate/compatibility/gen_type.go
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/types_authentication.go
  config/v1/types_feature.go
  config/v1/types_infrastructure.go
  config/v1/types_oauth.go
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.swagger_doc_generated.go
  dependencymagnet/doc.go
  image/v1/types.go
  legacyconfig/v1/types.go
  legacyconfig/v1/zz_generated.swagger_doc_generated.go
  networkoperator/v1/types_egressrouter.go
  operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  operator/v1/types_kubeapiserver.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#1326 operator: fix typo in kubeapiserver serviceaccountissuer field
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_kubeapiserver.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug

#1327 [release-4.9] operator: fix typo in kubeapiserver serviceaccountissuer field
  operator/v1/types_kubeapiserver.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1328 [release-4.10] operator: fix typo in kubeapiserver serviceaccountissuer field
  operator/v1/types_kubeapiserver.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1329 [release-4.11] operator: fix typo in kubeapiserver serviceaccountissuer field
  operator/v1/types_kubeapiserver.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
