Repository openshift/api, pull requests merged in 2022-02, with the labels that each got.

#1059 added Nutanix platform to openshift/api
  config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug

#1065 [OCPCLOUD-1354] Add Network Interface Type to AWS Machine Provider Spec
  machine/v1beta1/types_awsprovider.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1090 Update Dockerfile to account for Go 1.17 dependencies
  Dockerfile.build
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1104 Bug 2045551: Azure Disk and vSphere CSI drivers are GA
  config/v1/types_feature.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1106 config/v1/types_cluster_version: Add capabilties properties
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1115 CSI migration for Azure Disk and Cinder is GA in 4.11
  config/v1/types_feature.go
  config/v1/types_features_test.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1109 Add exceptions to compatibility level rules and fix security api compatibility levels
  cmd/openshift-compatibility-gen/generate/comment/generator.go
  security/v1/generated.proto
  security/v1/types.go
  security/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1121 Move console apis to tier 2, per what our docs say
  cmd/openshift-compatibility-gen/generate/comment/generator.go
  console/v1/0000_10_consoleclidownload.crd.yaml
  console/v1/0000_10_consoleexternalloglink.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/0000_10_consolequickstart.crd.yaml
  console/v1/0000_10_consoleyamlsample.crd.yaml
  console/v1/types_console_cli_download.go
  console/v1/types_console_external_log_links.go
  console/v1/types_console_link.go
  console/v1/types_console_notification.go
  console/v1/types_console_quick_start.go
  console/v1/types_console_yaml_sample.go
  console/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved
