Repository openshift/api, pull requests merged in 2022-07, with the labels that each got.

#1216 [OCPCLOUD-1586] Reintroduce and update ControlPlaneMachineSet API
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1/register.go
  machine/v1/types_aws.go
  machine/v1/types_controlplanemachineset.go
  machine/v1/zz_generated.deepcopy.go
  machine/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1206 Add a field in ClusterCSIDriver type to skip creation of storageclass
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/types_csi_cluster_driver.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1221 Bug 2104481: operator/ingress: Allow PROXY protocol for Private endpoint publishing strategy
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1223 Bug 2106086: operator/ingress: Fix healthCheckInterval pattern
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1207 Bug 1894268: Allow users to specify ovnkube join subnet
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved, docs-approved

#1102 Bug 1978798: Revert "Update ovnKubernetesConfig.policyAuditConfig Default"
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml-patch
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#1228 route/v1: Add CRD
  Makefile
  route/v1/generated.proto
  route/v1/route.crd.yaml
  route/v1/route.crd.yaml-patch
  route/v1/test-route-validation.sh
  route/v1/types.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1227 Bug 2100312: monitoring: include lowercase action in relabel_config validation
  monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  monitoring/v1alpha1/types.go
  monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1202 Changes to project helm repository so as to read secret from namespace
  helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  helm/v1beta1/types_project_helm_chart_repository.go
  helm/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug
