Repository openshift/api, pull requests merged in 2022-05, with the labels that each got.

#1187 removed the workerlatencyprofile status from the config node CR
  config/v1/0000_10_config-operator_01_node.crd.yaml
  config/v1/types_node.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1192 Add PowerVS Block CSI Driver to the config
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1179 monitoring: Add AlertingRule and AlertRelabelConfig types
  Makefile
  hack/lib/init.sh
  hack/update-deepcopy.sh
  install.go
  monitoring/install.go
  monitoring/v1alpha1/0000_50_monitoring_01_alertingrules.crd.yaml
  monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  monitoring/v1alpha1/doc.go
  monitoring/v1alpha1/register.go
  monitoring/v1alpha1/types.go
  monitoring/v1alpha1/zz_generated.deepcopy.go
  monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#1197 Bug 2082428: healthCheckInterval accepts invalid duration values
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1198 BZ 2088533: add subresource.status{} to sharedsecrets and sharedconfigmaps
  sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
  sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug

#1180 IR-234: Add spec.storage.s3.trustedCA to image registry config
  imageregistry/v1/00_imageregistry.crd.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved, qe-approved, docs-approved, px-approved
