Repository openshift/api, pull requests merged in 2023-06, with the labels that each got.

#1478 Add AlibabaPlatform feature gate to TechPreviewNoUpgrade
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1479 make the default DNS only install for default to avoid conflicts
  config/v1/0000_10_config-operator_01_dns.crd.yaml
Labels: size/XS, lgtm, approved

#1480 DNS: Fix hostedZoneRole regex Pattern
  config/v1/0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
  config/v1/techpreview.dns.testsuite.yaml
  config/v1/types_dns.go
Labels: lgtm, size/S, approved

#1456 STOR-1308: Add Secrets Store CSI driver provider
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1439 NE-1280: Add MaxLength field to ContainerLoggingDestinationParameters
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, ok-to-test, jira/valid-reference

#1489 WRKLDS-753: DeploymentConfigs deprecation in API reference docs
  apps/v1/generated.proto
  apps/v1/types.go
  apps/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XS, lgtm, approved, jira/valid-reference

#1428 OPNET-263: Enable CloudDualStackNodeIPs feature gate
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1434 OCPCLOUD-2010: Add CloudControllerManagerStatus to External platform status
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/feature_gates.go
  config/v1/techpreview.infrastructure.testsuite.yaml
  config/v1/types_feature.go
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/XL, approved, jira/valid-reference

#1490 Set up CustomNoUpgrade copies of CRDs
  config/.codegen.yaml
  config/v1/0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_dns-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_dns-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml-patch
  config/v1/stable.dns.testsuite.yaml
  config/v1/types_dns.go
  config/v1/types_infrastructure.go
  example/.codegen.yaml
  example/v1/0000_50_stabletype-CusomtNoUpgrade.crd.yaml
  example/v1/0000_50_stabletype-Default.crd.yaml
  example/v1/0000_50_stabletype-TechPreviewNoUpgrade.crd.yaml
  example/v1/stable.stableconfigtype.testsuite.yaml
  example/v1/techpreview.stableconfigtype.testsuite.yaml
  example/v1/types_stable.go
  tools/go.mod
  tools/go.sum
  tools/vendor/modules.txt
  tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/patch_validation.go
Labels: size/XXL, lgtm, approved

#1494 OCPBUGS-14716: Add ROSA branding option in console-operator config
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/types_console.go
Labels: lgtm, size/M, approved, jira/valid-bug, jira/valid-reference

#1495 Add AWSSecurityTokenService feature gate
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1496 OSASINFRA-3179: openstack failureDomain: Add RootVolume type
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  machine/v1/types_controlplanemachineset.go
  machine/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, jira/valid-reference

#1498 WRKLDS-757: Drop MatchLabelKeysInPodTopologySpread from TP, it is beta upstream now
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1338 SPLAT-843: Introduce static IP configuration to the vSphere provider spec
  config/v1/feature_gates.go
  config/v1/types_feature.go
  machine/v1beta1/types_machine.go
  machine/v1beta1/types_provider.go
  machine/v1beta1/types_vsphereprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, jira/valid-reference

#1505 [CNF-5643] add capability name to machine crd
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1beta1/0000_10_machine.crd.yaml
  machine/v1beta1/0000_10_machinehealthcheck.yaml
  machine/v1beta1/0000_10_machineset.crd.yaml
  tests/hack/test.sh
Labels: size/XS, lgtm, approved

#1509 openstack: Test no failure domains
  machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
Labels: lgtm, size/M, approved

#1510 OCPCLOUD-2113: Api changes to support placementGroupName for AWS machines
  machine/v1beta1/types_awsprovider.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XS, lgtm, approved, jira/valid-reference

#1512 deprecate operator/v1alpha.OperatorSpec|Status and related types
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1alpha1/types.go
  operator/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved
