Repository openshift/api, pull requests merged in 2023-04, with the labels that each got.

#1415 Add loadbalancer field to Power VS machine provider spec
  machine/v1/types_powervsprovider.go
  machine/v1/zz_generated.deepcopy.go
  machine/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/M, approved

#1435 Update storage vSphere driver validation
  operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  operator/v1/stable.storage.testsuite.yaml
  operator/v1/types_storage.go
Labels: lgtm, size/S, approved

#1440 OCPBUGS-11729: VSphereStorageDriver does not document the platform default
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  operator/v1/stable.storage.testsuite.yaml
  operator/v1/types_storage.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1441 OCPBUGS-11776: VSphereStorageDriver does not document the platform default
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  operator/v1/types_storage.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: size/XS, lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1447 Remove ValidatingAdmissionPolicy from tech preview.
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved

#1444 [OCPCLOUD-2034] Add Azure/GCP specific external cloud provider feature gates
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved

#1436 config/v1: Add AzureWorkloadIdentity to TechPreviewNoUpgrade
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved

#1448 strongly structure adding a new featuregate
  config/v1/feature_gates.go
  config/v1/feature_gates_test.go
  config/v1/types_feature.go
  config/v1/types_features_test.go
  config/v1/zz_generated.deepcopy.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved

#1450 fix some not-so-awesome typos
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved
