Repository openshift/api, pull requests merged in 2023-11, with the labels that each got.

#1599 STOR-1343: remove RetroactiveDefaultStorageClass feature gate
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1596 MCO-821: Introduce MachineConfigNode types
  machineconfiguration/.codegen.yaml
  machineconfiguration/install.go
  machineconfiguration/v1/types.go
  machineconfiguration/v1alpha1/0000_80_machineconfignode-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/0000_80_machineconfignode-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/Makefile
  machineconfiguration/v1alpha1/custom.machineconfignode.testsuite.yaml
  machineconfiguration/v1alpha1/doc.go
  machineconfiguration/v1alpha1/register.go
  machineconfiguration/v1alpha1/techpreview.machineconfignode.testsuite.yaml
  machineconfiguration/v1alpha1/types_machineconfignode.go
  machineconfiguration/v1alpha1/zz_generated.deepcopy.go
  machineconfiguration/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/XL, approved, jira/valid-reference

#1619 Add an informational message about schema validation failures
  hack/verify-crd-schema-checker.sh
Labels: size/XS, lgtm, approved

#1650 add comment to rebuild api image
  payload-command/render/render.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1651 OCPBUGS-22896: Add maxLogFiles config for OVN-K Audit Logging
  hack/update-protobuf.sh
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/S, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1615 MON-3410: Add FeatureGate for MetricsServer
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1653 Add AWS SDK Install Feature Gate
  config/v1/feature_gates.go
Labels: lgtm, size/S, approved

#1655 ClusterAPIInstall should not be in TechPreviewNoUpgrade
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved

#1657 SPLAT-1097: IBMCloud: Add IBM Cloud Service names
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/types.go
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, jira/valid-reference

#1642 bring openshift/api into the payload
  Dockerfile.rhel8
  manifests/image-references
Labels: size/XS, lgtm, approved

#1656 OCPBUGS-15934: use *resource.Quantity to not automatically set 0
  machineconfiguration/v1/types.go
  machineconfiguration/v1/zz_generated.deepcopy.go
Labels: size/XS, lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1662 make the render read yaml properly
  payload-command/render/renderassets/rendered_manifests.go
  payload-command/render/renderassets/rendered_manifests_test.go
Labels: lgtm, size/L, approved

#1664 backport the openshift owner anntotation
  annotations/annotations.go
Labels: size/XS, lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1658 Extend IPv6 validation in gateway subnet CRD
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
Labels: lgtm, size/M, approved

#1665 fix improper cast in render
  payload-command/render/render.go
Labels: lgtm, size/S, approved

#1663 SPLAT-1240: annotate default CRD with default feature-set annotation
  machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
Labels: size/XS, lgtm, approved, jira/valid-reference

#1668 features: add alternative installers to TP
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved

#1669 catch another non-yaml tolerant call
  payload-command/render/renderassets/assets.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1660 OCPBUGS-19358: Allow GIT_LFS_SKIP_SMUDGE environment variable
  build/v1/consts.go
Labels: size/XS, lgtm, approved, jira/valid-bug, jira/valid-reference

#1607 IR-367: add private storage account configuration options to image registry type
  imageregistry/v1/00_imageregistry.crd.yaml
  imageregistry/v1/stable.config.testsuite.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.deepcopy.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, jira/valid-reference

#1593 OPNET-351: Extend infra CR to store VIPs and MachineNetwork
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1578 Nutanix failure domains support
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  machine/v1/0000_10_controlplanemachineset-CustomNoUpgrade.crd.yaml
  machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
  machine/v1/0000_10_controlplanemachineset-TechPreviewNoUpgrade.crd.yaml
  machine/v1/types_controlplanemachineset.go
  machine/v1/types_nutanixprovider.go
  machine/v1/zz_generated.deepcopy.go
  machine/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/XL, approved

#1637 OCPBUGS-22364: Make MCO certificate observability fields optional for 4.15
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  machineconfiguration/v1/0000_80_machineconfigpool.crd.yaml
  machineconfiguration/v1/types.go
Labels: size/XS, lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#1649 STOR-1487: IBMCloud: Add CSIDriverConfig support for IBM Cloud
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/stable.clustercsidriver.testsuite.yaml
  operator/v1/types_csi_cluster_driver.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-reference

#1680 IR-367: add networkResourceGroupName to azure network access internal config
  imageregistry/v1/00_imageregistry.crd.yaml
  imageregistry/v1/stable.config.testsuite.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-reference

#1606 CORS-2429: Update GCP PlatformStatus for user provided dns
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/feature_gates.go
  config/v1/techpreview.infrastructure.testsuite.yaml
  config/v1/types_feature.go
  config/v1/types_infrastructure.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, jira/valid-reference

#1677 CORS-2979: Include AWS Alt Infra in Tech Preview
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1681 fix MCN CRD to use proper Drained and Cordoned condition types
  machineconfiguration/v1alpha1/0000_80_machineconfignode-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/0000_80_machineconfignode-TechPreviewNoUpgrade.crd.yaml
Labels: size/XS, lgtm, approved

#1659 OCPBUGS-12699: Add additional names to env var allow list
  build/v1/consts.go
Labels: size/XS, lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1679 Consistent minTLSVersion in IngressController CRD
  config/v1/0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  config/v1/types_apiserver.go
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1/0000_80_kubeletconfig.crd.yaml
  machineconfiguration/v1/types.go
  machineconfiguration/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
Labels: lgtm, size/M, approved, ok-to-test

#1640 NP-793: SDN live migration
  config/v1/0000_10_config-operator_01_network-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_network-Default.crd.yaml
  config/v1/0000_10_config-operator_01_network-TechPreviewNoUpgrade.crd.yaml
  config/v1/custom.network.testsuite.yaml
  config/v1/feature_gates.go
  config/v1/stable.network.testsuite.yaml
  config/v1/techpreview.network.testsuite.yaml
  config/v1/types_feature.go
  config/v1/types_network.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  operator/v1/custom.network.testsuite.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/techpreview.network.testsuite.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1684 CNF-10474:feature-gate: add mixedCPUs to feature gate
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1666 have the CVO manage CRDs from the api image
  Dockerfile.rhel8
Labels: do-not-merge/hold, size/S, approved

#1675 Add a mention of 'make generate-with-container' to the README file
  README.md
Labels: size/XS, lgtm, approved

#1477 CONSOLE-3652: Enable ConsolePlugin v1 CRD storage
  console/v1/90_consoleplugin.crd.yaml
  console/v1alpha1/90_consoleplugin.crd.yaml
Labels: size/XS, lgtm, approved, jira/valid-reference

#1646 add feature gate for MCO boot images updates
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1652 Remove Kuryr types
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved

#1641 AUTH-439: add an API for openID connect clients config
  config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  config/v1/custom.authentication.testsuite.yaml
  config/v1/techpreview.authentication.testsuite.yaml
  config/v1/types_authentication.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XXL, lgtm, approved, jira/valid-reference
