Repository openshift/api, pull requests merged in 2023-09, with the labels that each got.

#1499 SPLAT-1097: IBMCloud: Override IBM Cloud Service Endpoints
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, jira/valid-reference

#1587 Bump Kubernetes to 1.28.2
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/modules.txt
Labels: lgtm, size/S, approved, acknowledge-critical-fixes-only

#1588 Set kube-openapi version to match the one used in k8s 1.28.2
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#1575 OCPBUGS-16726: psa - move into tech preview for 4.14
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1590 [release-4.14] OCPBUGS-18798: Revert "Enable ValidatingAdmissionPolicy for tech preview."
  config/v1/types_feature.go
  hack/update-protobuf.sh
Labels: size/XS, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1567 Image and manifests
  .gitignore
  Dockerfile.rhel8
  Makefile
  go.mod
  manifests/image-references
  payload-command/cmd/render/main.go
  payload-command/cmd/write-available-featuresets/main.go
  payload-command/empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_authentication.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_build.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_console.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_dns.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_image.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_ingress.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_network.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_oauth.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_project.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_proxy.cr.yaml
  payload-command/empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
  payload-command/empty-resources/0000_10_config-operator_02_node.cr.yaml
  payload-command/render/config.go
  payload-command/render/render.go
  payload-command/render/renderassets/assets.go
  payload-command/render/renderassets/rendered_manifests.go
  payload-command/render/renderassets/template.go
  payload-command/render/renderassets/write.go
  payload-command/render/write_featureset.go
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/errors/doc.go
  vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1585 Add an owning-component annotation.
  annotations/annotations.go
Labels: size/XS, lgtm, approved

#1580 IR-401: remove references to OPENSHIFT_DEFAULT_REGISTRY
  config/v1/0000_10_config-operator_01_image.crd.yaml
  config/v1/types_image.go
  config/v1/zz_generated.swagger_doc_generated.go
  kubecontrolplane/v1/types.go
  kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  legacyconfig/v1/types.go
  legacyconfig/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  openshiftcontrolplane/v1/types.go
  openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-reference

#1544 helm/v1beta1: Rename files to use the default run-level for updates
  helm/v1beta1/00_helm-chart-repository.crd.yaml
  helm/v1beta1/00_project-helm-chart-repository.crd.yaml
  helm/v1beta1/stable.helmchartrepository.testsuite.yaml
  helm/v1beta1/stable.projecthelmchartrepository.testsuite.yaml
Labels: size/XS, lgtm, approved

#1542 schemapatch: Print file path if unmarshal fails
  tools/codegen/pkg/schemapatch/generator.go
Labels: size/XS, lgtm, approved

#1488 OCPCLOUD-1989: Promote GCP CCM from TPNU to default
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1532 OCPBUGS-15834: Bump runlevel for ConsolePlugin CRD
  console/v1/0000_51_consoleplugin.crd.yaml
  console/v1/stable.consoleplugin.testsuite.yaml
  console/v1alpha1/0000_51_consoleplugin.crd.yaml
  console/v1alpha1/stable.consoleplugin.testsuite.yaml
Labels: size/XS, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1453 MCO-52: add MCO API into openshift/api
  machineconfiguration/OWNERS
  machineconfiguration/install.go
  machineconfiguration/install_test.go
  machineconfiguration/v1/0000_80_containerruntimeconfig.crd.yaml
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  machineconfiguration/v1/0000_80_kubeletconfig.crd.yaml
  machineconfiguration/v1/0000_80_machineconfig.crd.yaml
  machineconfiguration/v1/0000_80_machineconfigpool.crd.yaml
  machineconfiguration/v1/doc.go
  machineconfiguration/v1/register.go
  machineconfiguration/v1/stable.containerruntimeconfig.testsuite.yaml
  machineconfiguration/v1/stable.controllerconfig.testsuite.yaml
  machineconfiguration/v1/stable.kubeletconfig.testsuite.yaml
  machineconfiguration/v1/stable.machineconfig.testsuite.yaml
  machineconfiguration/v1/stable.machineconfigpool.testsuite.yaml
  machineconfiguration/v1/types.go
  machineconfiguration/v1/zz_generated.deepcopy.go
  machineconfiguration/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_80_machine-config-operator_01_config.crd.yaml
  operator/v1/register.go
  operator/v1/stable.machineconfiguration.testsuite.yaml
  operator/v1/types.go
  operator/v1/types_machineconfiguration.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: size/XXL, lgtm, approved, jira/valid-reference
