Repository openshift/api, pull requests merged in 2023-05, with the labels that each got.

#1446 OSASINFRA-3152: move `loadBalancer` API to GA for OpenStack
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
Labels: lgtm, size/L, approved, jira/valid-reference

#1452 add GatewayAPI featureset
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1438 OCPBUGS-11393: Fix incorrect API usage documentation for insecureEdgeTerminationPolicy
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  route/v1/generated.proto
  route/v1/route.crd.yaml
  route/v1/route.crd.yaml-patch
  route/v1/stable.route.testsuite.yaml
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1429 OCPBUGS-6829: Add protocolStrategy for upstreams in dnses.operator.openshift.io
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_dns-operator_00.crd.yaml
  operator/v1/types_dns.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1449 [CNF-5643] add machine-api capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, size/M, approved

#1463 WRKLDS-746: TechPreviewNoUpgrade: enable MaxUnavailableStatefulSet
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1465 Add feature gate for AWS Private Hosted Zone support
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1468 OCPBUGS-3176: Add config knob for enabling ip forwarding
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/S, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1470 Add `SigstoreImageVerification` feature gate
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1471 Add Evented Pleg as a Tech Preview feature in the Openshift
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, do-not-merge/hold, size/S, approved

#1473 OCPBUGS-3176: Rework IP Forwarding config
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1474 CFE-685 : Add TechPreviewNoUpgrade featureGate for GCP Labels and Tags support
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1460 DNS: Add awsPrivateHostedZoneRole
  config/v1/0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
  config/v1/techpreview.dns.testsuite.yaml
  config/v1/types_dns.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved
