Repository openshift/api, pull requests merged in 2023-12, with the labels that each got.

#1571 OCPVE-645: add CloudCredential capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
  operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1694 OPNET-414: Revert "Extend infra CR to store VIPs and MachineNetwork"
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1693 Set DisableKubeletCloudCredentialProviders upstream feature gate to False
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1648 Add payload manifests dir
  Dockerfile.rhel8
  Makefile
  hack/update-payload-crds.sh
  hack/verify-payload-crds.sh
  payload-manifests/crds/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  payload-manifests/crds/0000_03_config-operator_01_proxy.crd.yaml
  payload-manifests/crds/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  payload-manifests/crds/0000_03_security-openshift_01_scc.crd.yaml
  payload-manifests/crds/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_config.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_console.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_dns-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_dns-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_featuregate.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_image.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_imagecontentpolicy.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_ingress.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_network-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_network-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_network-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_node.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_oauth.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_project.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_scheduler.crd.yaml
Labels: size/XXL, lgtm, approved

#1457 [OCPNODE-1671] Add ClusterImagePolicy and ImagePolicy
  config/v1alpha1/0000_10_config-operator_01_clusterimagepolicy-CustomNoUpgrade.crd.yaml
  config/v1alpha1/0000_10_config-operator_01_clusterimagepolicy-TechPreviewNoUpgrade.crd.yaml
  config/v1alpha1/0000_10_config-operator_01_imagepolicy-CustomNoUpgrade.crd.yaml
  config/v1alpha1/0000_10_config-operator_01_imagepolicy-TechPreviewNoUpgrade.crd.yaml
  config/v1alpha1/custom.clusterimagepolicy.testsuite.yaml
  config/v1alpha1/custom.imagepolicy.testsuite.yaml
  config/v1alpha1/techpreview.clusterimagepolicy.testsuite.yaml
  config/v1alpha1/techpreview.imagepolicy.testsuite.yaml
  config/v1alpha1/types_cluster_image_policy.go
  config/v1alpha1/types_image_policy.go
  config/v1alpha1/zz_generated.deepcopy.go
  config/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XXL, lgtm, approved

#1706 Add KMSv1 to default feature gates
  config/v1/feature_gates.go
  config/v1/types_feature.go
  payload-command/render/renderassets/rendered_manifests_test.go
Labels: lgtm, size/S, approved

#1708 OCPBUGS-24955: Updating ose-cluster-config-api-container image to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel8
  go.mod
  go.sum
Labels: lgtm, size/S, approved, jira/valid-bug, jira/valid-reference

#1703 MCO-838: Add feature gate for pinned images
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved, jira/valid-reference
