Repository openshift/api, pull requests merged in 2023-08, with the labels that each got.

#1540 NE-1303: Revert "cluster version: add ingress capability"
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operatoringress/v1/0000_50_dns-record.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1529 [release-4.13] DNS: Add awsPrivateHostedZoneRole
  config/v1/0000_10_config-operator_01_dns.crd.yaml
  config/v1/stable.dns.testsuite.yaml
  config/v1/types_dns.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1462 WRKLDS-728: Make Build and DeploymentConfig API optional through capabilities
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, size/M, approved, jira/valid-reference

#1541 CONSOLE-3717: Console CRDs: Rename files to use the default run-level for updates
  console/v1/00_consoleclidownload.crd.yaml
  console/v1/00_consoleexternalloglink.crd.yaml
  console/v1/00_consolelink.crd.yaml
  console/v1/00_consolenotification.crd.yaml
  console/v1/00_consolequickstart.crd.yaml
  console/v1/00_consolesample.crd.yaml
  console/v1/00_consoleyamlsample.crd.yaml
  console/v1/90_consoleplugin.crd.yaml
  console/v1/stable.consoleclidownload.testsuite.yaml
  console/v1/stable.consoleexternalloglink.testsuite.yaml
  console/v1/stable.consolelink.testsuite.yaml
  console/v1/stable.consolenotification.testsuite.yaml
  console/v1/stable.consoleplugin.testsuite.yaml
  console/v1/stable.consolequickstart.testsuite.yaml
  console/v1/stable.consolesample.testsuite.yaml
  console/v1/stable.consoleyamlsample.testsuite.yaml
  console/v1alpha1/90_consoleplugin.crd.yaml
  console/v1alpha1/stable.consoleplugin.testsuite.yaml
  operator/v1/00_console-operator.crd.yaml
  operator/v1/stable.console.testsuite.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1545 samples/v1: Rename files to use the default run-level for updates
  samples/v1/00_samplesconfig.crd.yaml
  samples/v1/stable.config.testsuite.yaml
Labels: size/XS, lgtm, approved

#1445 CFE-685 : Update Infrastructure CRD to support GCP labels and tags in status
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/custom.infrastructure.testsuite.yaml
  config/v1/techpreview.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/XL, approved

#1549 OCPBUGS-17414: Limit header names to 255 characters
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.swagger_doc_generated.go
  route/v1/generated.proto
  route/v1/route-CustomNoUpgrade.crd.yaml
  route/v1/route-TechPreviewNoUpgrade.crd.yaml
  route/v1/route.crd.yaml
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-bug, jira/valid-reference

#1550 WRKLDS-727: add controller names
  openshiftcontrolplane/v1/types.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1443 OCPBUGS-12205: remove techpreview from cpu partitioning
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
Labels: lgtm, size/S, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1552 [WRKLDS-707] remove PDBUnhealthyPodEvictionPolicy feature gate from TechPreviewNoUpgrade
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1554 OCPBUGS-15654: Add MAPI to all capability sets
  config/v1/types_cluster_version.go
Labels: size/XS, lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1538 Adding etcd tuning profiles api
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  operator/v1/techpreview.etcd.testsuite.yaml
  operator/v1/types_etcd.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved

#1557 Extend integration test timeout to 30m
  tests/hack/test.sh
Labels: size/XS, lgtm, approved

#1537 Ensure baremetal cap is not enabled without MachineAPI cap
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/stable.clusterversion.testsuite.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, size/L, approved

#1466 CNF-9384: add ImageRegistry capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1558 Introduce ValidatingAdmissionPolicy gate as disabled.
  config/v1/feature_gates.go
  config/v1/types_feature.go
Labels: lgtm, size/S, approved

#1526 OCPCLOUD-2130: CPMS: Add subnet to azure FailureDomain
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1/types_controlplanemachineset.go
  machine/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/S, approved, jira/valid-reference

#1553 BUILD-689: Promote BuildCSIVolumes featureGate to GA
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1559 Enable ValidatingAdmissionPolicy for tech preview.
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved

#1562 OCPBUGS-17806: Revert "add ImageRegistry capability"
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, size/S, approved, jira/valid-bug, jira/valid-reference

#1551 OCPSTRAT-660: AWS Shared VPC [release-4.12]
  config/v1/0000_10_config-operator_01_dns.crd.yaml
  config/v1/stable.dns.testsuite.yaml
  config/v1/types_dns.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1410 OCPBUGS-18093:Allow users to specify Gateway Subnet
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, jira/valid-bug, jira/valid-reference

#1568 Split CRD schema check into separate Makefile target
  Makefile
Labels: size/XS, lgtm, approved

#1572 Add back ImageRegistry capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, size/S, approved

#1563 CCO-412: Promote azureWorkloadIdentity to defaultFeatures.
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved, jira/valid-reference
