Repository openshift/api, pull requests merged in 2024-08, with the labels that each got.

#1975 MCO-1065: MCO-1171: Promoting ManagedBootImages and NodeDisruptionPolicy to default featureset
  features.md
  features/features.go
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, qe-approved, jira/valid-reference

#1972 Add MCP and Config Version columns to MCN output
  machineconfiguration/v1alpha1/types_machineconfignode.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineconfignodes.machineconfiguration.openshift.io/MachineConfigNodes.yaml
Labels: lgtm, size/M, approved, ¯\_(ツ)_/¯

#1984 featuregate promotion: use latest release instead of hard coding
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: lgtm, size/M, approved

#1952 OCPBUGS-35906: a rule to check if the featureSet is one of the known set of features
  config/v1/tests/featuregates.config.openshift.io/AAA_ungated.yaml
  config/v1/types_feature.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_featuregates.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/featuregates.config.openshift.io/AAA_ungated.yaml
  payload-manifests/crds/0000_10_config-operator_01_featuregates.crd.yaml
Labels: lgtm, size/M, approved, jira/valid-bug, jira/valid-reference

#1966 NE-1774: Promote `IngressControllerLBSubnetsAWS` to GA
  features.md
  features/features.go
  operator/v1/types_ingress.go
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-Default.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/L, approved, qe-approved, jira/valid-reference

#1958 CORS-3594: Setting CAPG as the default infra provider
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1974 Run update-payload-crds after update-codegen-crds
  Makefile
Labels: size/XS, lgtm, approved

#1948 IR-471: Removing featuregate for chunkSizeMiB config
  features.md
  features/features.go
  imageregistry/v1/zz_generated.crd-manifests/00_configs-CustomNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-Default.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-TechPreviewNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved, qe-approved, jira/valid-reference

#1926 [release-4.14] CFE-1047: Added new field for capacityReservationGroupID in AzureMachineProviderSpec
  machine/v1beta1/types_azureprovider.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/S, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1980 AUTH-527: security/v1 - add constant for enforcing psa annotation
  security/v1/consts.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1986 SDN-5186: Add OVNObservability feature gate as Tech Preview.
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1989 NE-1794: Promote `eipAllocations` API in GA
  features.md
  features/features.go
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved, qe-approved, jira/valid-reference

#1853 STOR-1422: Add field for enabling EFS volume metrics
  features.md
  features/features.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/tests/clustercsidrivers.operator.openshift.io/AWSEFSDriverVolumeMetrics.yaml
  operator/v1/types_csi_cluster_driver.go
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/clustercsidrivers.operator.openshift.io/AWSEFSDriverVolumeMetrics.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1987 CORS-3617: Promote Azure CAPI as the default Install method
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1979 Power VS: Move Power VS to CAPI by default
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved

#1991 MULTIARCH-4776: MULTIARCH-4770: installer: promote MultiArchInstall FGs
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1971 CFE-921: Enable GCPLabelsTags featureGate by default for GA
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  features.md
  features/features.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/L, approved, qe-approved, jira/valid-reference

#1988 SDN-4919,SDN-5135: Graduate `UserDefinedNetworks` to GA
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1597 extend the example integration test with set of strings attribute
  example/v1/0000_50_stabletype-CustomNoUpgrade.crd.yaml
  example/v1/0000_50_stabletype-Default.crd.yaml
  example/v1/0000_50_stabletype-TechPreviewNoUpgrade.crd.yaml
  example/v1/stable.stableconfigtype.testsuite.yaml
  example/v1/types_stable.go
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-CustomNoUpgrade.crd.yaml
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-Default.crd.yaml
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-DevPreviewNoUpgrade.crd.yaml
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-TechPreviewNoUpgrade.crd.yaml
  example/v1/zz_generated.deepcopy.go
  example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/AAA_ungated.yaml
  example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/Example.yaml
  example/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/XL, approved

#1996 OCPBUGS-38414: Revert #1988 "Graduate `UserDefinedNetworks` to GA"
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-bug, jira/valid-reference

#2000 featuregate analyzer: use correct platform name
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: size/XS, lgtm, approved

#1959 OCPBUGS-36479: remove duplicate featuregate 'ExternalRouteCertificate'
  README.md
  features.md
  features/features.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
  route/v1/generated.proto
  route/v1/tests/routes.route.openshift.io/RouteExternalCertificate.yaml
  route/v1/types.go
  route/v1/zz_generated.crd-manifests/routes-CustomNoUpgrade.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-Default.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-DevPreviewNoUpgrade.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-TechPreviewNoUpgrade.crd.yaml
  route/v1/zz_generated.featuregated-crd-manifests.yaml
  route/v1/zz_generated.featuregated-crd-manifests/routes.route.openshift.io/AAA_ungated.yaml
  route/v1/zz_generated.featuregated-crd-manifests/routes.route.openshift.io/RouteExternalCertificate.yaml
Labels: lgtm, size/L, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2001 Update envtest publishing to create index file
  envtest-releases.yaml
  tools/Makefile
  tools/publish-kubebuilder-tools/README.md
  tools/publish-kubebuilder-tools/main.go
Labels: lgtm, size/L, approved

#2003 featuregate analyzer: fix platform name for metal
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: lgtm, size/S, approved

#1780 OCPCLOUD-2561: Remove CloudProviderExternal feature gates
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#1981 clean up openshift-sdn references in the API
  config/v1/types_network.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkDiagnosticsConfig.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkLiveMigration.yaml
  config/v1/zz_generated.swagger_doc_generated.go
  network/v1/generated.proto
  network/v1/types.go
  network/v1/zz_generated.crd-manifests/001_clusternetworks.crd.yaml
  network/v1/zz_generated.crd-manifests/002_hostsubnets.crd.yaml
  network/v1/zz_generated.crd-manifests/003_netnamespaces.crd.yaml
  network/v1/zz_generated.crd-manifests/004_egressnetworkpolicies.crd.yaml
  network/v1/zz_generated.featuregated-crd-manifests/clusternetworks.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.featuregated-crd-manifests/egressnetworkpolicies.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.featuregated-crd-manifests/hostsubnets.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.featuregated-crd-manifests/netnamespaces.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_network.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AdditionalRoutingCapabilities.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/RouteAdvertisements.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
  payload-manifests/crds/0000_10_config-operator_01_networks.crd.yaml
Labels: size/XXL, lgtm, approved

#2009 featuregate analyzer: use 1 week lookback if possible
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: lgtm, size/S, approved

#2011 OCPBUGS-38958: [4.17] add UserNamespacesSupport/ProcMountType to tech preview features
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/M, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1943 OCPNODE-2400: Add Conditions field to the config.node object's status
  config/v1/types_node.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes.crd.yaml
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.featuregated-crd-manifests/nodes.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/crds/0000_10_config-operator_01_nodes.crd.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#2006 OCPBUGS-37773: Added checks to prevent vCenters from changing after install past 1 vCenter
  config/v1/tests/infrastructures.config.openshift.io/VSphereMultiVCenters.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/BareMetalLoadBalancer.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPLabelsTags.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereMultiVCenters.yaml
  config/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/BareMetalLoadBalancer.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPClusterHostedDNS.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPLabelsTags.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereMultiVCenters.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
Labels: lgtm, size/XL, approved, jira/valid-bug, jira/valid-reference

#2015 CONSOLE-4055: Add "Getting started resources" console capability
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_console.go
  operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/consoles.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-reference

#2008 OCPBUGS-39300: clean up openshift-sdn references in the API [4.17]
  config/v1/types_network.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkDiagnosticsConfig.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkLiveMigration.yaml
  config/v1/zz_generated.swagger_doc_generated.go
  network/v1/generated.proto
  network/v1/types.go
  network/v1/zz_generated.crd-manifests/001_clusternetworks.crd.yaml
  network/v1/zz_generated.crd-manifests/002_hostsubnets.crd.yaml
  network/v1/zz_generated.crd-manifests/003_netnamespaces.crd.yaml
  network/v1/zz_generated.crd-manifests/004_egressnetworkpolicies.crd.yaml
  network/v1/zz_generated.featuregated-crd-manifests/clusternetworks.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.featuregated-crd-manifests/egressnetworkpolicies.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.featuregated-crd-manifests/hostsubnets.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.featuregated-crd-manifests/netnamespaces.network.openshift.io/AAA_ungated.yaml
  network/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_network.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AdditionalRoutingCapabilities.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/RouteAdvertisements.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
  payload-manifests/crds/0000_10_config-operator_01_networks.crd.yaml
Labels: size/XXL, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
