Repository openshift/api, pull requests merged in 2024-05, with the labels that each got.

#1789 MCO-1148: Attempt to tombstone MachineConfiguration/StaticPodOperatorStatus
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_machineconfiguration.go
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/ManagedBootImages.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/NodeDisruptionPolicy.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1875 Recurse when loading CRD schemas to check
  tools/codegen/pkg/schemacheck/generator.go
Labels: lgtm, size/M, approved

#1876 Add Machine V1 to payload CRDs
  hack/update-payload-crds.sh
  payload-manifests/crds/0000_10_control-plane-machine-set_01_controlplanemachinesets.crd.yaml
Labels: do-not-merge/hold, size/XL, approved

#1877 Update imageregistry component SSA tags
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.crd-manifests/00_configs.crd.yaml
  imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/AAA_ungated.yaml
Labels: lgtm, size/S, approved

#1864 Expose chunksize variable for S3 storage driver
  features.md
  features/features.go
  imageregistry/v1/tests/configs.imageregistry.operator.openshift.io/ChunkSizeMiB.yaml
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.crd-manifests/00_configs-CustomNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-Default.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-DevPreviewNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-TechPreviewNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.featuregated-crd-manifests.yaml
  imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/ChunkSizeMiB.yaml
  imageregistry/v1/zz_generated.swagger_doc_generated.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: size/XXL, lgtm, approved

#1881 Update SSA tag markers
  imageregistry/v1/types.go
  imageregistry/v1/zz_generated.crd-manifests/00_configs-CustomNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-Default.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-DevPreviewNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-TechPreviewNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/AAA_ungated.yaml
  imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/ChunkSizeMiB.yaml
Labels: lgtm, size/S, approved

#1874 ETCD-520: add BackendQuotaGiB example
  example/v1/tests/stableconfigtypes.example.openshift.io/-Example.yaml
  example/v1/tests/stableconfigtypes.example.openshift.io/AAA_ungated.yaml
  example/v1/tests/stableconfigtypes.example.openshift.io/Example.yaml
  example/v1/types_stable.go
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-CustomNoUpgrade.crd.yaml
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-Default.crd.yaml
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-DevPreviewNoUpgrade.crd.yaml
  example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-TechPreviewNoUpgrade.crd.yaml
  example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/AAA_ungated.yaml
  example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/Example.yaml
  example/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/M, approved, jira/valid-reference

#1882 add MachineConfiguration conditions for boot image updates
  operator/v1/types_machineconfiguration.go
Labels: lgtm, size/S, approved

#1885 NO-JIRA: Update runtime image and drop color in CI
  Makefile
  tests/hack/test.sh
Labels: size/XS, lgtm, approved, jira/valid-reference

#1880 Add eligible CAPI-install platforms to TechPreview
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved

#1889 CORS-3488: Add GCP CAPI installer to tech preview feature set.
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1865 Revert "Revert "Merge pull request #1851 from slashpai/metrics-server""
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, qe-approved, acknowledge-critical-fixes-only

#1886 SDN-4600: Add NetworkDiagnosticsConfig to the default featureset
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml
  features.md
  features/features.go
  payload-manifests/crds/0000_10_config-operator_01_networks-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_networks-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_networks-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_networks.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1890 NO-JIRA: Set listType for .status.serviceNetwork and .status.clusterNetwork in networks.config
  config/v1/types_network.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkDiagnosticsConfig.yaml
  config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkLiveMigration.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/crds/0000_10_config-operator_01_networks.crd.yaml
Labels: lgtm, size/M, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1894 OCPBUGS-33727: Fix Gateway API Feature Gate
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1892 Move CAPI install platforms to default feature set
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/M, approved, acknowledge-critical-fixes-only

#1896 NO-JIRA: Enable the ibm-cloud-managed cluster profile on network.operator CRD
  operator/v1/types_network.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
Labels: size/XS, lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1888 API-1783: Promote ValidatingAdmissionPolicy to GA
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1844 ETCD-488: Move etcd hardware speed feature to GA
  features.md
  features/features.go
  operator/v1/tests/etcds.operator.openshift.io/HardwareSpeed.yaml
  operator/v1/zz_generated.crd-manifests/0000_12_etcd_01_etcds-Default.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/M, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1856 remove console v1alpha1 which was present since 4.12
  console/install.go
  console/v1alpha1/Makefile
  console/v1alpha1/doc.go
  console/v1alpha1/manual-override-crd-manifests/consoleplugins.console.openshift.io/AAA_ungated.yaml
  console/v1alpha1/register.go
  console/v1alpha1/tests/consoleplugins.console.openshift.io/AAA_ungated.yaml
  console/v1alpha1/types.go
  console/v1alpha1/types_console_plugin.go
  console/v1alpha1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  console/v1alpha1/zz_generated.crd-manifests/doc.go
  console/v1alpha1/zz_generated.deepcopy.go
  console/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  console/v1alpha1/zz_generated.featuregated-crd-manifests/consoleplugins.console.openshift.io/AAA_ungated.yaml
  console/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XXL, lgtm, approved

#1866 CFE-1047: Add the field "CapacityReservationGroupID" to "AzureMachineProviderSpec" in openshift/api
  machine/v1beta1/types_azureprovider.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/S, approved, jira/valid-reference

#1751 [release-4.15] OCPBUGS-28928: Add UnservableInFutureVersions route status condition type
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  route/v1/generated.proto
  route/v1/route-CustomNoUpgrade.crd.yaml
  route/v1/route-TechPreviewNoUpgrade.crd.yaml
  route/v1/route.crd.yaml
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/S, approved, lifecycle/stale, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1902 STOR-1839: promote VSphereDriverConfiguration feature to Accessible-by-default
  features.md
  features/features.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_csi_cluster_driver.go
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/clustercsidrivers.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/clustercsidrivers.operator.openshift.io/VSphereDriverConfiguration.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved, qe-approved, jira/valid-reference

#1887 OCPBUGS-33787: add console and download URLs to console operator config
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/tests/consoles.operator.openshift.io/AAA_ungated.yaml
  operator/v1/types_console.go
  operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests/consoles.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1906 API-1783: Bump 1.30.1
  config/v1/zz_generated.crd-manifests/0000_10_openshift-controller-manager_01_builds.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/builds.config.openshift.io/AAA_ungated.yaml
  go.mod
  go.sum
  imageregistry/v1/zz_generated.crd-manifests/00_configs-CustomNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-Default.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-DevPreviewNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.crd-manifests/00_configs-TechPreviewNoUpgrade.crd.yaml
  imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/AAA_ungated.yaml
  imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/ChunkSizeMiB.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, size/L, approved, jira/valid-reference

#1895 Feature gates for platforms, architecture, and installs
  tools/codegen/cmd/featuregate-test-analyzer.go
  tools/codegen/cmd/featuregate-test-analyzer_test.go
  tools/codegen/pkg/sippy/json_types.go
Labels: lgtm, size/L, approved

#1907 Adds conditions to MachineSet
  machine/v1beta1/types_machineset.go
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-CustomNoUpgrade.crd.yaml
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-Default.crd.yaml
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-DevPreviewNoUpgrade.crd.yaml
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-TechPreviewNoUpgrade.crd.yaml
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.featuregated-crd-manifests/machinesets.machine.openshift.io/AAA_ungated.yaml
  machine/v1beta1/zz_generated.featuregated-crd-manifests/machinesets.machine.openshift.io/MachineAPIMigration.yaml
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved

#1911 temporarily break the featuregate check to show we can get results
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
