Repository openshift/api, pull requests merged in 2024-09, with the labels that each got.

#1950 CORS-3582: remove unused installer feature gates
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2013 Promote AWSEFSDriverVolumeMetrics to GA
  features.md
  features/features.go
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved

#2019 features: update psa and byoo owners
  features/features.go
Labels: size/XS, lgtm, approved

#2020 [release-4.17] OCPBUGS-38355: Promote AWSEFSDriverVolumeMetrics to GA
  features.md
  features/features.go
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved, cherry-pick-approved, staff-eng-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1962 OCPBUGS-41360: [release-4.14]Backport subnet configs
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/XL, approved, cherry-pick-approved, staff-eng-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2017 WRKLDS-1449: add ObjectMeta to authorization and security types
  authorization/v1/generated.pb.go
  authorization/v1/generated.proto
  authorization/v1/types.go
  authorization/v1/zz_generated.deepcopy.go
  authorization/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  security/v1/generated.pb.go
  security/v1/generated.proto
  security/v1/types.go
  security/v1/zz_generated.deepcopy.go
  security/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-reference

#1976 add new feature for the Insights Runtime Extractor
  README.md
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved

#2018 features: disable PSA
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2022 OCPBUGS-41111: config/v1/types_cluster_version: Add v4.17 and v4.18 capability sets
  config/v1/types_cluster_version.go
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/SignatureStores.yaml
Labels: lgtm, size/M, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#2023 OCPBUGS-41642: config/v1/types_cluster_version: Add v4.17 capability set
  config/v1/types_cluster_version.go
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/SignatureStores.yaml
Labels: lgtm, size/M, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#2030 NO-jIRA: move some operator crds to openshift/api
  hack/update-payload-crds.sh
  payload-manifests/crds/0000_10_config-operator_01_backups-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_backups-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_backups-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_etcd_01_etcdbackups-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_etcd_01_etcdbackups-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_etcd_01_etcdbackups-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_openshift-controller-manager_01_builds.crd.yaml
  payload-manifests/crds/0000_12_etcd_01_etcds-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_12_etcd_01_etcds-Default.crd.yaml
  payload-manifests/crds/0000_12_etcd_01_etcds-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_12_etcd_01_etcds-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_20_kube-apiserver_01_kubeapiservers.crd.yaml
  payload-manifests/crds/0000_25_kube-controller-manager_01_kubecontrollermanagers.crd.yaml
  payload-manifests/crds/0000_25_kube-scheduler_01_kubeschedulers.crd.yaml
  payload-manifests/crds/0000_30_openshift-apiserver_01_openshiftapiservers.crd.yaml
  payload-manifests/crds/0000_50_authentication_01_authentications.crd.yaml
  payload-manifests/crds/0000_50_openshift-controller-manager_02_openshiftcontrollermanagers.crd.yaml
Labels: size/XXL, do-not-merge/hold, approved, jira/valid-reference

#2033 copy mco crds to be managed by openshfit/api
  hack/update-payload-crds.sh
  payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_containerruntimeconfigs.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_kubeletconfigs.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-Default.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigs.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigurations.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
Labels: size/XXL, lgtm, approved

#2032 NO-JIRA: move storage CRDs to openshift/api
  hack/update-payload-crds.sh
  payload-manifests/crds/0000_50_storage_01_storages.crd.yaml
  payload-manifests/crds/0000_90_csi-driver_01_clustercsidrivers.crd.yaml
Labels: lgtm, size/XL, approved, jira/valid-reference

#2040 OCPBUGS-41261: update NoNewRequiredFields comparator and bring additional comparators
  tools/go.mod
  tools/go.sum
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/defaultcomparators/interfaces.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_conditions_must_have_proper_ssa_tags.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_lists_must_have_ssa_tags.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_must_have_status.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_no_bools.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_no_enum_removal.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_no_field_removal.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_no_floats.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_no_maps.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_no_new_required_fields.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/comp_no_uints.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/helpers.go
  tools/vendor/github.com/openshift/crd-schema-checker/pkg/manifestcomparators/simple_tester.go
  tools/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  tools/vendor/modules.txt
Labels: lgtm, size/XL, approved, jira/valid-bug, jira/valid-reference

#2027 RFE-6242: add `OpenStackLoadBalancerParameters` to ingress API
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_ingress.go
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/SetEIPForNLBIngressController.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, jira/valid-reference
