Repository openshift/api, pull requests merged in 2024-03, with the labels that each got.

#1579 OCPVE-658: add CloudController capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion-CustomNoUpgrade.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion-Default.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion-TechPreviewNoUpgrade.crd.yaml
  config/v1/types_cluster_version.go
Labels: lgtm, size/S, approved, jira/valid-reference

#1730 OCPBUGS-25594: Fix text and indentation for TLS Security Profile
  config/v1/0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  config/v1/types_tlssecurityprofile.go
  config/v1/zz_generated.swagger_doc_generated.go
  hack/verify-protobuf.sh
  machineconfiguration/v1/0000_80_kubeletconfig.crd.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
Labels: lgtm, size/L, approved, qe-approved, jira/valid-bug, jira/valid-reference

#1784 remove ungated case from manifest-merge
  cloudnetwork/.codegen.yaml
  config/.codegen.yaml
  config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  config/v1/0000_10_config-operator_01_dns-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_dns.crd.yaml
  config/v1/custom.apiserver.testsuite.yaml
  config/v1/custom.dns.testsuite.yaml
  config/v1/stable.apiserver.testsuite.yaml
  config/v1/stable.dns.testsuite.yaml
  config/v1/techpreview.apiserver.testsuite.yaml
  config/v1/techpreview.dns.testsuite.yaml
  config/v1/types_cluster_operator.go
  config/v1/types_cluster_version.go
  config/v1/zz_generated.featuregated-crd-manifests.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusteroperators.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/SignatureStores.yaml
  machine/.codegen.yaml
  machine/v1/0000_10_controlplanemachineset-CustomNoUpgrade.crd.yaml
  machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
  machine/v1/0000_10_controlplanemachineset.crd.yaml
  machine/v1/custom.controlplanemachineset.testsuite.yaml
  machine/v1/stable.controlplanemachineset.aws.testsuite.yaml
  machine/v1/stable.controlplanemachineset.azure.testsuite.yaml
  machine/v1/stable.controlplanemachineset.gcp.testsuite.yaml
  machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  machine/v1/stable.controlplanemachineset.testsuite.yaml
  machine/v1/techpreview.controlplanemachineset.testsuite.yaml
  machine/v1/types_controlplanemachineset.go
  machine/v1/zz_generated.featuregated-crd-manifests.yaml
  machine/v1/zz_generated.featuregated-crd-manifests/controlplanemachinesets.machine.openshift.io/AAA_ungated.yaml
  operator/.codegen.yaml
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/custom.network.testsuite.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/techpreview.network.testsuite.yaml
  operator/v1/types_authentication.go
  operator/v1/types_network.go
  operator/v1/zz_generated.featuregated-crd-manifests.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/authentications.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
  operatoringress/.codegen.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_apiserver.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_dns-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_dns.crd.yaml
  platform/.codegen.yaml
  platform/v1alpha1/types.go
  platform/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  platform/v1alpha1/zz_generated.featuregated-crd-manifests/platformoperators.platform.openshift.io/PlatformOperators.yaml
  tools/codegen/pkg/generation/types.go
  tools/codegen/pkg/manifestmerge/generator.go
Labels: size/XXL, lgtm, approved

#1790 make the serialized featuregate location an input param
  tools/codegen/cmd/crd_manifest_merge.go
  tools/codegen/pkg/manifestmerge/filters.go
  tools/codegen/pkg/manifestmerge/generator.go
Labels: lgtm, size/M, approved

#1788 specify Featuregates by cluster profile
  config/v1/feature_gates.go
  config/v1/feature_gates_test.go
  config/v1/types_feature.go
  config/v1/types_features_test.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-command/render/render.go
  payload-command/render/write_featureset.go
  payload-manifests/featuregates/featureGate-CustomNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Default-Hypershift.yaml
  payload-manifests/featuregates/featureGate-Default-SelfManagedHA.yaml
  payload-manifests/featuregates/featureGate-Default-SingleNode.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade-Hypershift.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade-SelfManagedHA.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade-SingleNode.yaml
Labels: size/XXL, lgtm, approved

#1801 tighten up the useCRD interface
  tools/codegen/pkg/manifestmerge/filters.go
  tools/codegen/pkg/manifestmerge/generator.go
Labels: lgtm, size/M, approved

#1729 SPLAT-1293: Moved vSphereStaticIPs into Default from TechPreview
  config/v1/feature_gates.go
  payload-manifests/featuregates/featureGate-Default-Hypershift.yaml
  payload-manifests/featuregates/featureGate-Default-SelfManagedHA.yaml
  payload-manifests/featuregates/featureGate-Default-SingleNode.yaml
  payload-manifests/featuregates/featureGate-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1757 OPNET-466: PlatformLoadBalancer becomes GA for On-Prem
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/feature_gates.go
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/techpreview.infrastructure.testsuite.yaml
  machineconfiguration/v1/0000_80_controllerconfig-Default.crd.yaml
  machineconfiguration/v1/stable.controllerconfig.testsuite.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  payload-manifests/featuregates/featureGate-Default-Hypershift.yaml
  payload-manifests/featuregates/featureGate-Default-SelfManagedHA.yaml
  payload-manifests/featuregates/featureGate-Default-SingleNode.yaml
  payload-manifests/featuregates/featureGate-Default.yaml
Labels: lgtm, size/XL, approved, qe-approved, jira/valid-reference

#1805 make featuregate manifest pattern consistent and remove legacy files
  payload-command/render/write_featureset.go
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SingleNode-Default.yaml
  payload-manifests/featuregates/featureGate-SingleNode-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
  tools/codegen/pkg/manifestmerge/filters.go
Labels: lgtm, size/L, approved

#1802 Move config v1 IP validation to CEL
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/techpreview.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/BareMetalLoadBalancer.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPLabelsTags.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
  machineconfiguration/v1/0000_80_controllerconfig-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/0000_80_controllerconfig-Default.crd.yaml
  machineconfiguration/v1/0000_80_controllerconfig-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/BareMetalLoadBalancer.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPClusterHostedDNS.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPLabelsTags.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
Labels: size/XXL, lgtm, approved, acknowledge-critical-fixes-only

#1806 skip rendering mutation of CustomNoUpgrade featuresets
  payload-command/render/render.go
Labels: lgtm, size/L, approved, acknowledge-critical-fixes-only

#1810 TRT-1563: Revert #1802 "Move config v1 IP validation to CEL"
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/techpreview.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/BareMetalLoadBalancer.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPLabelsTags.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_controllerconfig-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_controllerconfig-Default.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_controllerconfig-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/BareMetalLoadBalancer.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPClusterHostedDNS.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPLabelsTags.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1815 add section about adding new APIs
  README.md
Labels: lgtm, size/L, approved, acknowledge-critical-fixes-only

#1792 BUILD-854: Updates to build API reviewers
  build/OWNERS
Labels: size/XS, lgtm, approved, cherry-pick-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1816 explain roughly what the new generator is doing
  README.md
Labels: lgtm, size/M, approved, acknowledge-critical-fixes-only

#1820 add markdown generator for featuregates
  features.md
  hack/update-payload-featuregates.sh
  hack/verify-payload-featuregates.sh
  payload-command/render/render.go
  tools/codegen/cmd/featureset-markdown.go
  tools/codegen/pkg/manifestmerge/filters.go
  tools/codegen/pkg/manifestmerge/generator.go
  tools/codegen/pkg/utils/featureset.go
  tools/codegen/pkg/utils/markdown.go
Labels: lgtm, size/XL, approved, acknowledge-critical-fixes-only

#1823 NO-JIRA: Switch integration tests to ordered to save time
  tests/generator.go
Labels: size/XS, lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1822 MCO-838: machineconfiguration/v1alpha1: add PinnedImageSet
  machineconfiguration/v1/Makefile
  machineconfiguration/v1/custom.machineconfigpool.testsuite.yaml
  machineconfiguration/v1/stable.machineconfigpool.testsuite.yaml
  machineconfiguration/v1/techpreview.machineconfigpool.testsuite.yaml
  machineconfiguration/v1/types.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-Default.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.deepcopy.go
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfigpools.machineconfiguration.openshift.io/PinnedImages.yaml
  machineconfiguration/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1alpha1/custom.pinnedimageset.testsuite.yaml
  machineconfiguration/v1alpha1/register.go
  machineconfiguration/v1alpha1/techpreview.pinnedimageset.testsuite.yaml
  machineconfiguration/v1alpha1/types_pinnedimageset.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.deepcopy.go
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/pinnedimagesets.machineconfiguration.openshift.io/PinnedImages.yaml
  machineconfiguration/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: size/XXL, lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1830 machineconfiguration/v1alpha1: add PinnedImageSetStatus
  machineconfiguration/v1alpha1/types_pinnedimageset.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.deepcopy.go
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/pinnedimagesets.machineconfiguration.openshift.io/PinnedImages.yaml
  machineconfiguration/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved

#1828 Add models-schema to make clean
  Makefile
Labels: size/XS, lgtm, approved

#1835 MON-3486: add feature gate for Collection Profiles
  config/v1/feature_gates.go
  features.md
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1670 MON-3486: add feature gate for Collection Profiles
  config/v1/feature_gates.go
  features.md
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, jira/valid-reference

#1786 OCPCLOUD-2573: Enables kubelet cloud credential providers
  config/v1/feature_gates.go
  features.md
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1831 NO-JIRA: enable the SA token node thing
  config/v1/feature_gates.go
  features.md
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1839 use CEL to enforce immutable featureset
  config/v1/tests/featuregates.config.openshift.io/AAA_ungated.yaml
  config/v1/types_feature.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_featuregates.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/featuregates.config.openshift.io/AAA_ungated.yaml
  payload-manifests/crds/0000_10_config-operator_01_featuregates.crd.yaml
Labels: lgtm, size/L, approved
