Repository openshift/api, pull requests merged in 2024-06, with the labels that each got.

#1912 OCPBUGS-26466: Disable PSA in non-previews 4.16
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1913 CNV-41151: ipam, virt: add persistent ips feature gate
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1872 OCPBUGS-35214: [Release 4-15] Add transit switch config to 4.15
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/XL, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1924 Update published Kubebuilder tools
  tools/Makefile
Labels: size/XS, lgtm, approved

#1897 CFE-1063: Add PlacementGroupPartition in AWSMachineProviderConfig
  machine/v1beta1/types_awsprovider.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/S, approved, jira/valid-reference

#1934 NO-JIRA: remove beta enabled features from feature gates
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1916 METAL-1038 Remove baremetal dependency on MachineAPI capability
  config/v1/tests/clusterversions.config.openshift.io/AAA_ungated.yaml
  config/v1/tests/clusterversions.config.openshift.io/SignatureStores.yaml
  config/v1/types_cluster_version.go
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/SignatureStores.yaml
Labels: lgtm, size/L, approved
