Repository openshift/api, pull requests merged in 2024-01, with the labels that each got.

#1654 [release 4.12] OCPBUGS-23025: Add maxLogFiles config for OVN-K Audit Logging
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/S, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1695 OPNET-415: Revert the revert "Extend infra CR to store VIPs and MachineNetwork""
  config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  config/v1/stable.infrastructure.testsuite.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  machineconfiguration/v1/0000_80_controllerconfig-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/0000_80_controllerconfig-Default.crd.yaml
  machineconfiguration/v1/0000_80_controllerconfig-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1716 AUTH-439: authentication: use CRD validation for the 'type' field
  config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  config/v1/0000_10_config-operator_01_authentication.crd.yaml
  config/v1/custom.authentication.testsuite.yaml
  config/v1/stable.authentication.testsuite.yaml
  config/v1/techpreview.authentication.testsuite.yaml
  config/v1/types_authentication.go
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1667 add-IPsecExternal
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved

#1717 OCPBUGS-26441: disable psa
  config/v1/types_feature.go
Labels: size/XS, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1720 Add generated featuregate files inertly to payloads
  Dockerfile.rhel8
  Makefile
  hack/update-payload-featuregates.sh
  hack/verify-payload-featuregates.sh
  payload-command/render/config.go
  payload-manifests/featuregates/featureGate-CustomNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-LatencySensitive.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved

#1723 Add generated featuregate files inertly to payloads
  Dockerfile.rhel8
  Makefile
  hack/update-payload-featuregates.sh
  hack/verify-payload-featuregates.sh
  payload-command/render/config.go
  payload-manifests/featuregates/featureGate-CustomNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-LatencySensitive.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1726 Add ImagePolicyList and ClusterImagePolicyList to scheme known types
  config/v1alpha1/register.go
Labels: size/XS, lgtm, approved

#1697 SPLAT-1385: introduce TagIDs field to vSphere providerSpec
  machine/v1beta1/types_vsphereprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/S, approved, jira/valid-reference

#1725 OTA-1169: Add feature gate for upgrade status
  config/v1/feature_gates.go
  config/v1/types_feature.go
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-LatencySensitive.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#1734 OCPBUGS-27366: respect the cluster profile in rendering
  payload-command/cmd/render/main.go
  payload-command/render/render.go
  payload-command/render/renderassets/assets.go
  payload-command/render/renderassets/write.go
Labels: lgtm, size/M, approved, jira/valid-bug, jira/valid-reference

#1506 CFE-857: Add new param ResourceManagerTags to GCPMachineProviderSpec
  machine/v1beta1/types_gcpprovider.go
  machine/v1beta1/zz_generated.deepcopy.go
  machine/v1beta1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/M, approved, jira/valid-reference

#1737 OCPBUGS-27468: features: enabled TranslateStreamCloseWebsocketRequests through TechPreviewNoUpgrade
  config/v1/feature_gates.go
  config/v1/types_feature.go
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-LatencySensitive.yaml
  payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-bug, jira/valid-reference

#1733 SPLAT-1396: promote feature gate and vSphere failure domains to default
  config/v1/types_feature.go
  machine/v1/0000_10_controlplanemachineset-CustomNoUpgrade.crd.yaml
  machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
  machine/v1/0000_10_controlplanemachineset-TechPreviewNoUpgrade.crd.yaml
  machine/v1/types_controlplanemachineset.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-LatencySensitive.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1727 OCPBUGS-27222: Allow modified IPv6 address as CPIC name
  cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
Labels: size/XS, lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
