Repository openshift/api, pull requests merged in 2024-04, with the labels that each got.

#1819 OCPBUGS-31058: config/ingress: Make Hostname godoc user-friendly
  config/v1/types_ingress.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_ingresses.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/ingresses.config.openshift.io/AAA_ungated.yaml
  payload-manifests/crds/0000_10_config-operator_01_ingresses.crd.yaml
Labels: lgtm, size/M, approved, jira/valid-bug, jira/valid-reference

#1626 Proposed new api structure for ovnkubernetes / transit switch api
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/tests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: size/XXL, lgtm, approved

#1840 SDN-4596: Promote `AdminNetworkPolicy` to GA
  config/v1/feature_gates.go
  features.md
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, qe-approved, jira/valid-reference

#1824 MCO-838: machineconfiguration/v1alpha1: add PinnedImageSet to MCN
  machineconfiguration/v1/types.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfigpools.machineconfiguration.openshift.io/PinnedImages.yaml
  machineconfiguration/v1alpha1/tests/machineconfignodes.machineconfiguration.openshift.io/MachineConfigNodes.yaml
  machineconfiguration/v1alpha1/types_machineconfignode.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.deepcopy.go
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineconfignodes.machineconfiguration.openshift.io/MachineConfigNodes.yaml
  machineconfiguration/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/XL, approved, jira/valid-reference

#1829 OCPBUGS-28673: Ingress - add connect timeout to tuning options
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/tests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, jira/valid-bug, jira/valid-reference

#1770 OCPBUILD-9: Adds seperate controllers for default rolebindings
  openshiftcontrolplane/v1/types.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1850 MCO API Cleanup
  machineconfiguration/v1alpha1/types_machineosbuild.go
  machineconfiguration/v1alpha1/types_machineosconfig.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosbuilds.machineconfiguration.openshift.io/OnClusterBuild.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/S, approved

#1848 NO-JIRA: add type for recording tests per featuregate
  config/v1/types_testreporting.go
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/L, approved, jira/valid-reference

#1843 NO-JIRA: add command to restrict features from promotion without tests
  Makefile
  hack/verify-promoted-features-pass-tests.sh
  tools/codegen/cmd/featuregate-test-analyzer.go
  tools/codegen/cmd/featuregate-test-analyzer_test.go
  tools/codegen/cmd/featureset-markdown.go
  tools/codegen/pkg/sippy/json_types.go
  tools/codegen/pkg/utils/markdown.go
  tools/go.mod
  tools/go.sum
  tools/vendor/github.com/russross/blackfriday/.gitignore
  tools/vendor/github.com/russross/blackfriday/.travis.yml
  tools/vendor/github.com/russross/blackfriday/LICENSE.txt
  tools/vendor/github.com/russross/blackfriday/README.md
  tools/vendor/github.com/russross/blackfriday/block.go
  tools/vendor/github.com/russross/blackfriday/doc.go
  tools/vendor/github.com/russross/blackfriday/esc.go
  tools/vendor/github.com/russross/blackfriday/html.go
  tools/vendor/github.com/russross/blackfriday/inline.go
  tools/vendor/github.com/russross/blackfriday/markdown.go
  tools/vendor/github.com/russross/blackfriday/node.go
  tools/vendor/github.com/russross/blackfriday/smartypants.go
  tools/vendor/github.com/shurcooL/sanitized_anchor_name/.travis.yml
  tools/vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  tools/vendor/github.com/shurcooL/sanitized_anchor_name/README.md
  tools/vendor/github.com/shurcooL/sanitized_anchor_name/main.go
  tools/vendor/modules.txt
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1783 STOR-1803: add vsphere snapshot configuration fields to ClusterCSIDriver
  config/v1/feature_gates.go
  features.md
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/tests/clustercsidrivers.operator.openshift.io/VSphereDriverConfiguration.yaml
  operator/v1/types_csi_cluster_driver.go
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/clustercsidrivers.operator.openshift.io/VSphereDriverConfiguration.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference

#1852 MCO-838: machineconfig/v1: add PoolSynchronizers to MCP status
  machineconfiguration/v1/tests/machineconfigpools.machineconfiguration.openshift.io/PinnedImages.yaml
  machineconfiguration/v1/types.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.deepcopy.go
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfigpools.machineconfiguration.openshift.io/PinnedImages.yaml
  machineconfiguration/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, jira/valid-reference

#1855 add explanation of how to provide automated testing for FeatureGate
  README.md
Labels: lgtm, size/S, approved

#1854 remove alpha level of AlertingRules which are GA since 4.14
  config/v1/feature_gates.go
  features.md
  monitoring/install.go
  monitoring/v1alpha1/Makefile
  monitoring/v1alpha1/doc.go
  monitoring/v1alpha1/register.go
  monitoring/v1alpha1/tests/alertingrules.monitoring.openshift.io/AlertingRules.yaml
  monitoring/v1alpha1/tests/alertrelabelconfigs.monitoring.openshift.io/AlertingRules.yaml
  monitoring/v1alpha1/types.go
  monitoring/v1alpha1/zz_generated.crd-manifests/0000_50_monitoring_01_alertingrules-CustomNoUpgrade.crd.yaml
  monitoring/v1alpha1/zz_generated.crd-manifests/0000_50_monitoring_01_alertingrules-TechPreviewNoUpgrade.crd.yaml
  monitoring/v1alpha1/zz_generated.crd-manifests/0000_50_monitoring_02_alertrelabelconfigs-CustomNoUpgrade.crd.yaml
  monitoring/v1alpha1/zz_generated.crd-manifests/0000_50_monitoring_02_alertrelabelconfigs-TechPreviewNoUpgrade.crd.yaml
  monitoring/v1alpha1/zz_generated.crd-manifests/doc.go
  monitoring/v1alpha1/zz_generated.deepcopy.go
  monitoring/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  monitoring/v1alpha1/zz_generated.featuregated-crd-manifests/alertingrules.monitoring.openshift.io/AlertingRules.yaml
  monitoring/v1alpha1/zz_generated.featuregated-crd-manifests/alertrelabelconfigs.monitoring.openshift.io/AlertingRules.yaml
  monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: size/XXL, lgtm, approved

#1817 OCPBUGS-30954: Reintroduce CEL IP/CIDR validation for Config APIs
  config/v1/tests/infrastructures.config.openshift.io/AAA_ungated.yaml
  config/v1/tests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/BareMetalLoadBalancer.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPLabelsTags.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/BareMetalLoadBalancer.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPClusterHostedDNS.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPLabelsTags.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
Labels: size/XXL, lgtm, approved, jira/valid-bug, jira/valid-reference

#1860 Provide a small help when invoking tests/hack/gen-minimal-test.sh
  tests/hack/gen-minimal-test.sh
Labels: lgtm, size/S, approved

#1851 MON-3538: Promote MetricsServer FeatureGate to GA
  config/v1/feature_gates.go
  features.md
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, qe-approved, jira/valid-reference

#1861 NO-JIRA: Change PreviousFlakePercentage value type from int to float
  tools/codegen/pkg/sippy/json_types.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1867 fix MachineOSBuild printer columns
  machineconfiguration/v1alpha1/types_machineosbuild.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosbuilds.machineconfiguration.openshift.io/OnClusterBuild.yaml
Labels: lgtm, size/M, approved

#1870 clean up NodeDisruptionPolicySpecAction godoc
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_machineconfiguration.go
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/NodeDisruptionPolicy.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved

#1871 Simplify CEL validations in network operator
  operator/v1/tests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/types_network.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
Labels: lgtm, size/XL, approved

#1868 features: add capi-installer gate per platform
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved

#1845 OCPBUGS-31666: route: Fix insecureEdgeTerminationPolicy default
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  route/v1/generated.proto
  route/v1/types.go
  route/v1/zz_generated.crd-manifests/routes-CustomNoUpgrade.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-Default.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-DevPreviewNoUpgrade.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-TechPreviewNoUpgrade.crd.yaml
  route/v1/zz_generated.featuregated-crd-manifests/routes.route.openshift.io/AAA_ungated.yaml
  route/v1/zz_generated.featuregated-crd-manifests/routes.route.openshift.io/ExternalRouteCertificate.yaml
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/M, approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#1873 OPNET-512: config/v1/types_infrastructure: change set to atomic for networks
  config/v1/types_infrastructure.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/BareMetalLoadBalancer.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPLabelsTags.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/BareMetalLoadBalancer.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPClusterHostedDNS.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPLabelsTags.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference
