Repository openshift/api, pull requests merged in 2024-02, with the labels that each got.

#1747 NP-874: Promote SDN Live Migration to GA
  config/v1/types_feature.go
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-LatencySensitive.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1722 OCPBUGS-26498: Add UnservableInFutureVersions route status condition type
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  route/v1/generated.proto
  route/v1/route-CustomNoUpgrade.crd.yaml
  route/v1/route-TechPreviewNoUpgrade.crd.yaml
  route/v1/route.crd.yaml
  route/v1/types.go
  route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/S, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1750 OCPBUGS-28902: Allow modified IPv6 address as CPIC name
  cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
Labels: size/XS, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1749 NP-905: [release-4.15] Promote Live Migration to GA
  config/v1/types_feature.go
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
  payload-manifests/featuregates/featureGate-Default.yaml
  payload-manifests/featuregates/featureGate-LatencySensitive.yaml
Labels: lgtm, size/S, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1752 OCPBUGS-18991: Add BuildInterrupted type
  machineconfiguration/v1/types.go
Labels: size/XS, lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1755 OCPBUGS-29075: Move network.config status.conditions to GA
  config/v1/0000_10_config-operator_01_network-Default.crd.yaml
  config/v1/stable.network.testsuite.yaml
  config/v1/types_network.go
  payload-manifests/crds/0000_10_config-operator_01_network-Default.crd.yaml
Labels: lgtm, size/L, approved, jira/valid-bug, jira/valid-reference

#1756 [release-4.15] OCPBUGS-29074: Move network.config conditions to GA
  config/v1/0000_10_config-operator_01_network-Default.crd.yaml
  config/v1/stable.network.testsuite.yaml
  config/v1/types_network.go
  payload-manifests/crds/0000_10_config-operator_01_network-Default.crd.yaml
Labels: lgtm, size/L, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1741 STOR-1724: Add Samba/CIFS CSI driver provider
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  operator/v1/types_csi_cluster_driver.go
Labels: size/XS, lgtm, approved, jira/valid-reference

#1754 To Install helmcharts through Samples operator
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  samples/v1/00_samplesconfig.crd.yaml
  samples/v1/generated.pb.go
  samples/v1/generated.proto
  samples/v1/stable.config.testsuite.yaml
  samples/v1/types_config.go
  samples/v1/zz_generated.deepcopy.go
  samples/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, tide/merge-method-squash

#1762 OCPBUGS-21029: Revert "Console CRDs: Rename files to use the default run-level for updates"
  console/v1/0000_10_consoleclidownload.crd.yaml
  console/v1/0000_10_consoleexternalloglink.crd.yaml
  console/v1/0000_10_consolelink.crd.yaml
  console/v1/0000_10_consolenotification.crd.yaml
  console/v1/0000_10_consoleplugin.crd.yaml
  console/v1/0000_10_consolequickstart.crd.yaml
  console/v1/0000_10_consolesample.crd.yaml
  console/v1/0000_10_consoleyamlsample.crd.yaml
  console/v1/stable.consoleclidownload.testsuite.yaml
  console/v1/stable.consoleexternalloglink.testsuite.yaml
  console/v1/stable.consolelink.testsuite.yaml
  console/v1/stable.consolenotification.testsuite.yaml
  console/v1/stable.consoleplugin.testsuite.yaml
  console/v1/stable.consolequickstart.testsuite.yaml
  console/v1/stable.consolesample.testsuite.yaml
  console/v1/stable.consoleyamlsample.testsuite.yaml
  console/v1alpha1/0000_10_consoleplugin.crd.yaml
  console/v1alpha1/stable.consoleplugin.testsuite.yaml
  operator/v1/0000_70_console-operator.crd.yaml
  operator/v1/stable.console.testsuite.yaml
Labels: lgtm, size/S, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1759 SPLAT-1441: promote vSphere failure domain template field
  config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  config/v1/types_infrastructure.go
  machineconfiguration/v1/0000_80_controllerconfig-Default.crd.yaml
  machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructure-Default.crd.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1740 OCPBUGS-29196: Update AWSCSIDriverConfigSpec fields validation to accept all current AWS partitions
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/types_csi_cluster_driver.go
Labels: size/XS, lgtm, approved, ok-to-test, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1724 NE-1303: cluster version: add v4.16 set and ingress capability
  config/v1/0000_00_cluster-version-operator_01_clusterversion-CustomNoUpgrade.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion-Default.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion-TechPreviewNoUpgrade.crd.yaml
  config/v1/types_cluster_version.go
  operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  operatoringress/v1/0000_50_dns-record.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#1753 config/v1/types_cluster_version: Drop never-implemented 'Evaluating' conditionalUpdates condition type
  config/v1/0000_00_cluster-version-operator_01_clusterversion-CustomNoUpgrade.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion-Default.crd.yaml
  config/v1/0000_00_cluster-version-operator_01_clusterversion-TechPreviewNoUpgrade.crd.yaml
  config/v1/types_cluster_version.go
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/S, approved

#1771 OCPBUGS-29435: allow multiple audiences to be configured for kube-apiserver
  config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
  config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml-patch
  config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  config/v1/types_authentication.go
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-bug, jira/valid-reference

#1765 [OCPNODE-1671] ImagePolicy uses byte format for base64 fields
  config/v1alpha1/0000_10_config-operator_01_clusterimagepolicy-CustomNoUpgrade.crd.yaml
  config/v1alpha1/0000_10_config-operator_01_clusterimagepolicy-TechPreviewNoUpgrade.crd.yaml
  config/v1alpha1/0000_10_config-operator_01_imagepolicy-CustomNoUpgrade.crd.yaml
  config/v1alpha1/0000_10_config-operator_01_imagepolicy-TechPreviewNoUpgrade.crd.yaml
  config/v1alpha1/types_image_policy.go
  config/v1alpha1/zz_generated.deepcopy.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: lgtm, size/M, approved

#1772 OCPBUGS-29435: allow multiple audiences to be configured for kube-apiserver
  config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
  config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml-patch
  config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  config/v1/types_authentication.go
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1691 OCPBUGS-23788: Only allow valid values for gatewayConfig.ipForwarding
  operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  operator/v1/stable.network.testsuite.yaml
  operator/v1/types_network.go
Labels: lgtm, size/L, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1767 [4.15] OCPBUGS-29370: Update AWSCSIDriverConfigSpec fields validation to accept all current AWS partitions
  operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  operator/v1/types_csi_cluster_driver.go
Labels: size/XS, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
