Repository openshift/api, pull requests merged in 2025-06, with the labels that each got.

#2350 Remove DataGather state print column
  insights/v1alpha2/types_insights.go
  insights/v1alpha2/zz_generated.crd-manifests/0000_10_insights_01_datagathers-CustomNoUpgrade.crd.yaml
  insights/v1alpha2/zz_generated.crd-manifests/0000_10_insights_01_datagathers-DevPreviewNoUpgrade.crd.yaml
  insights/v1alpha2/zz_generated.crd-manifests/0000_10_insights_01_datagathers-TechPreviewNoUpgrade.crd.yaml
  insights/v1alpha2/zz_generated.featuregated-crd-manifests.yaml
  insights/v1alpha2/zz_generated.featuregated-crd-manifests/datagathers.insights.openshift.io/InsightsOnDemandDataGather.yaml
Labels: lgtm, size/S, approved

#2354 SPLAT-2137: FG for Service Type LB NLB with Security Group
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2225 Promote RouteAdvertisements feature gate to default feature set
  features.md
  features/features.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved

#2352 CNTRLPLANE-337: authentication: oidc: make username claim mapping required
  config/v1/tests/authentications.config.openshift.io/ExternalOIDC.yaml
  config/v1/tests/authentications.config.openshift.io/ExternalOIDCWithUIDAndExtraClaimMappings.yaml
  config/v1/types_authentication.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-SelfManagedHA-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-SelfManagedHA-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-SelfManagedHA-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.deepcopy.go
  config/v1/zz_generated.featuregated-crd-manifests/authentications.config.openshift.io/ExternalOIDC.yaml
  config/v1/zz_generated.featuregated-crd-manifests/authentications.config.openshift.io/ExternalOIDCWithUIDAndExtraClaimMappings.yaml
  config/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentications-SelfManagedHA-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentications-SelfManagedHA-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_authentications-SelfManagedHA-TechPreviewNoUpgrade.crd.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#2338 OCPBUGS-55652: Remove PrivateHostedZoneAWS feature gate
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2349 Register MutatingAdmissionPolicy in feature gates
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/M, approved

#2359 OCPBUGS-55663: Remove NodeDisruptionPolicy featuregate
  features.md
  features/features.go
  features/legacyfeaturegates.go
  operator/v1/tests/machineconfigurations.operator.openshift.io/NodeDisruptionPolicy.yaml
  operator/v1/types_machineconfiguration.go
  operator/v1/zz_generated.featuregated-crd-manifests.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/ManagedBootImages.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/NodeDisruptionPolicy.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: size/XXL, lgtm, approved, jira/valid-bug, jira/valid-reference

#2363 [release-4.17] OCPBUGS-57285: Add IPsec API for NAT-T UDP encapsulation support
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_network.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  operator/v1/zz_generated.deepcopy.go
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AdditionalRoutingCapabilities.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/RouteAdvertisements.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2373 Adding feature gate for image mode status reporting
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved

#2288 MCO-1064: Promote MachineConfigNode feature gate to default
  features.md
  features/features.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference

#2269 MCO-1524: Promote PinnedImageSet feature gate to default feature set
  features.md
  features/features.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigpools.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_pinnedimagesets.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfigpools.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference

#2320 OCPBUGS-34194: Modify api description for join, transit and masquerade subnets
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/types_network.go
  operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AdditionalRoutingCapabilities.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/RouteAdvertisements.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2138 CNTRLPLANE-72: remove RoleBindingRestriction CRD from payload
  hack/update-payload-crds.sh
  payload-manifests/crds/0000_03_config-operator_01_rolebindingrestrictions.crd.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#2382 STOR-2370: Add featuregates for storage performant security policies
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference
