Repository openshift/api, pull requests merged in 2025-04, with the labels that each got.

#2181 OCPNODE-2877: Remove support to configure cgroupsv1 in OCP
  config/v1/tests/nodes.config.openshift.io/AAA_ungated.yaml
  config/v1/types_node.go
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-CustomNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-Default.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-DevPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-TechPreviewNoUpgrade.crd.yaml
  config/v1/zz_generated.featuregated-crd-manifests/nodes.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/nodes.config.openshift.io/MinimumKubeletVersion.yaml
  payload-manifests/crds/0000_10_config-operator_01_nodes-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_nodes-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_nodes-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_nodes-TechPreviewNoUpgrade.crd.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#2256 NO ISSUE: Tombstone `Spec.PinnedImageSets` in MCN v1alpha1 API
  machineconfiguration/v1alpha1/tests/machineconfignodes.machineconfiguration.openshift.io/MachineConfigNodes.yaml
  machineconfiguration/v1alpha1/types_machineconfignode.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.deepcopy.go
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineconfignodes.machineconfiguration.openshift.io/MachineConfigNodes.yaml
  machineconfiguration/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
Labels: lgtm, size/L, approved

#2260 NO-ISSUE: tools: bump openshift controller-tools to latest commit
  tools/go.mod
  tools/go.sum
  tools/vendor/modules.txt
  tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/patch_schema.go
Labels: lgtm, size/M, approved, jira/valid-reference

#2104 IBMCloud: Add IBM Cloud CAPI install TechPreview FG
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved

#2236 SPLAT-2079: Removed VSphereControlPlaneMachineSet feature gate
  config/v1/tests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
  config/v1/types_infrastructure.go
  config/v1/zz_generated.featuregated-crd-manifests.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AAA_ungated.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AWSClusterHostedDNS.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/BareMetalLoadBalancer.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/DualReplica.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/DyanmicServiceEndpointIBMCloud.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPCustomAPIEndpoints.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPLabelsTags.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/HighlyAvailableArbiter.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/NutanixMultiSubnets.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereHostVMGroupZonal.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereMultiNetworks.yaml
  config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereMultiVCenters.yaml
  features.md
  features/features.go
  machineconfiguration/v1/tests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AWSClusterHostedDNS.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/BareMetalLoadBalancer.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/DualReplica.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/DyanmicServiceEndpointIBMCloud.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPClusterHostedDNS.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPCustomAPIEndpoints.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPLabelsTags.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/HighlyAvailableArbiter.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/NutanixMultiSubnets.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereMultiNetworks.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereMultiVCenters.yaml
  payload-command/render/renderassets/rendered_manifests_test.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference

#2242 OPRUN-3780: Add feature flag for NewOLMPreflightPermissionCheck
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2267 OCPBUGS-54784: [release-4.18] Bump openshift/controller-tools to latest commit
  tools/go.mod
  tools/go.sum
  tools/vendor/modules.txt
  tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/patch_schema.go
Labels: lgtm, size/M, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2261 NE-2009: Enable GatewayAPI featuregate in Default featureset
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2240 image/v1/types: improve documentation
  image/v1/generated.proto
  image/v1/types.go
  image/v1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
Labels: needs-ok-to-test, lgtm, size/S, approved

#2276 Temporarily pin feature-gate-analyzer to 4.19
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: lgtm, size/S, approved

#2277 TRT-2081: Revert #2261 "NE-2009: Enable GatewayAPI featuregate in Default featureset"
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2281 NE-2009: Re-enable GatewayAPI featuregate in Default featureset
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2192 Promote OnClusterBuild featuregate to default
  features.md
  features/features.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-CustomNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-DevPreviewNoUpgrade.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosbuilds.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: size/XXL, lgtm, approved

#2286 MON-4071: GA `MetricsCollectionProfiles`
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2275 CONSOLE-4523: Lift Featuregate for the ConsolePlugin ContentSecurityPolicy API
  console/v1/zz_generated.crd-manifests/90_consoleplugins-CustomNoUpgrade.crd.yaml
  console/v1/zz_generated.crd-manifests/90_consoleplugins-Default.crd.yaml
  console/v1/zz_generated.crd-manifests/90_consoleplugins-TechPreviewNoUpgrade.crd.yaml
  console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/XL, approved, jira/valid-reference

#2268 OAPE-92: Promote RouteExternalCertificate feature gate to default feature set
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  route/v1/zz_generated.crd-manifests/routes-Default.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-DevPreviewNoUpgrade.crd.yaml
  route/v1/zz_generated.crd-manifests/routes-TechPreviewNoUpgrade.crd.yaml
  route/v1/zz_generated.crd-manifests/routes.crd.yaml
Labels: size/XXL, lgtm, approved, jira/valid-reference

#2279 OCPCLOUD-2914: Add MAPI to CAPI migration to TechPreview
  features.md
  features/features.go
  machine/v1/tests/controlplanemachinesets.machine.openshift.io/CPMSMachineNamePrefix.yaml
  machine/v1/zz_generated.crd-manifests/0000_10_control-plane-machine-set_01_controlplanemachinesets-DevPreviewNoUpgrade.crd.yaml
  machine/v1/zz_generated.crd-manifests/0000_10_control-plane-machine-set_01_controlplanemachinesets-TechPreviewNoUpgrade.crd.yaml
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machines-DevPreviewNoUpgrade.crd.yaml
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machines-TechPreviewNoUpgrade.crd.yaml
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-DevPreviewNoUpgrade.crd.yaml
  machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_control-plane-machine-set_01_controlplanemachinesets-DevPreviewNoUpgrade.crd.yaml
  payload-manifests/crds/0000_10_control-plane-machine-set_01_controlplanemachinesets-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#2254 OAPE-148: Promote CPMSMachineNamePrefix feature gate to default feature set
  features.md
  features/features.go
  machine/v1/zz_generated.crd-manifests/0000_10_control-plane-machine-set_01_controlplanemachinesets-Default.crd.yaml
  payload-manifests/crds/0000_10_control-plane-machine-set_01_controlplanemachinesets-Default.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/M, approved, jira/valid-reference

#2296 Fix broken ControlPlaneMachineSet integration tests
  machine/v1/tests/controlplanemachinesets.machine.openshift.io/CPMSMachineNamePrefix.yaml
Labels: size/XS, lgtm, approved

#2264 OPRUN-3766: Add FeatureFlag for OLMv1 Single/OwnNamespace
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2186 [release-4.17] OCPBUGS-49702: Add IdleConnectionTerminationPolicy field to IngressControllerSpec
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  operator/v1/tests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
  operator/v1/tests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
  operator/v1/tests/ingresscontrollers.operator.openshift.io/SetEIPForNLBIngressController.yaml
  operator/v1/types_ingress.go
  operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
  operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/SetEIPForNLBIngressController.yaml
  operator/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/L, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2139 OCPBUGS-48286: feature-gates - enable ServiceAccountTokenNodeBinding
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
