Repository openshift/api, pull requests merged in 2025-08, with the labels that each got.

#2406 OCPNODE-3006: add back SigstoreImageVerification to techPreview
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2401 OCPEDGE-1945: feat: promote HighlyAvailableArbiter feature to default
  config/v1/tests/infrastructures.config.openshift.io/DualReplica.yaml
  config/v1/tests/infrastructures.config.openshift.io/HighlyAvailableArbiter+DualReplica.yaml
  config/v1/tests/infrastructures.config.openshift.io/HighlyAvailableArbiter.yaml
  config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  features.md
  features/features.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  payload-manifests/crds/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: lgtm, size/L, approved, jira/valid-reference

#2426 STOR-2481: Promote SELinuxMount feature gate
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2437 Remove OnClusterBuild fg
  features.md
  features/features.go
  features/legacyfeaturegates.go
  machineconfiguration/install.go
  machineconfiguration/v1/tests/machineosbuilds.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/tests/machineosconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/types_machineosbuild.go
  machineconfiguration/v1/types_machineosconfig.go
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosbuilds.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1alpha1/register.go
  machineconfiguration/v1alpha1/tests/machineosbuilds.machineconfiguration.openshift.io/OnClusterBuild.yaml
  machineconfiguration/v1alpha1/tests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
  machineconfiguration/v1alpha1/types_machineosbuild.go
  machineconfiguration/v1alpha1/types_machineosconfig.go
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
  machineconfiguration/v1alpha1/zz_generated.deepcopy.go
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosbuilds.machineconfiguration.openshift.io/OnClusterBuild.yaml
  machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
  machineconfiguration/v1alpha1/zz_generated.swagger_doc_generated.go
  openapi/generated_openapi/zz_generated.openapi.go
  openapi/openapi.json
  payload-command/render/legacyfeaturegates.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: size/XXL, lgtm, approved

#2399 OCPBUGS-54287: MachineOSConfig name should match MachineConfigPool
  machineconfiguration/v1/tests/machineosconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  machineconfiguration/v1/types_machineosconfig.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs.crd.yaml
Labels: lgtm, size/L, approved, jira/valid-bug, jira/valid-reference

#2445 Fix feature promotion check single node variant name
  tools/codegen/cmd/featuregate-test-analyzer.go
Labels: size/XS, lgtm, approved

#2455 OWNERS: update approvers/reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#2453 OCPNODE-3121: Graduate ImageVolume to GA
  features.md
  features/features.go
  payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
Labels: lgtm, size/S, approved, jira/valid-reference

#2457 OTA-923: Promote `ClusterVersionOperatorConfiguration` to TechPreview
  features.md
  features/features.go
  operator/v1alpha1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversionoperators-TechPreviewNoUpgrade.crd.yaml
  payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
  payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#2449 [release-4.19] OCPBUGS-60414: MachineOSConfig name should match MachineConfigPool
  machineconfiguration/v1/tests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
  machineconfiguration/v1/types_machineosconfig.go
  machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
  machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
  payload-manifests/crds/0000_80_machine-config_01_machineosconfigs.crd.yaml
Labels: lgtm, size/L, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
